<?php
/** Open Learning II — v4.3.36. */
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class SC_Library_Open_Learning_II {
    public const VERSION='4.3.36';
    public const SCHEMA='sc-library-open-learning-v2/1.0';
    public const ROUTE_SCHEMA='sc-library-learning-route/1.0';
    public const MANIFEST_SCHEMA='sc-library-learning-route-manifest/1.0';
    public const REST_NAMESPACE='sc-library/v1';
    public const REST_ROUTE='/open-learning-v2';
    public const USER_META='sc_library_learning_routes_v4336';
    public const COURSE_PLAN_META='sc_library_course_plan_v4321';
    public const MAX_ROUTES=50;
    public const MAX_COURSES_PER_ROUTE=8;
    private const ROUTE_STATUSES=array('planned'=>'Planned','active'=>'Active','completed'=>'Completed','archived'=>'Archived');
    private const ACCESS_PREFERENCES=array('open-first'=>'Open-first','free-any'=>'Any free-access model','any'=>'Any listed access model');

    public function __construct(){
        add_action('wp_enqueue_scripts',array($this,'register_assets'));
        add_action('rest_api_init',array($this,'register_rest_routes'));
        add_shortcode('sc_open_learning_ii',array($this,'shortcode'));
        add_filter('sc_library_open_learning_plan',array($this,'filter_learning_plan'),10,2);
        add_filter('sc_library_open_learning_route_manifest',array($this,'filter_route_manifest'),10,3);
    }
    public function register_assets(){
        wp_register_style('sc-library-open-learning-v2-v4336',SC_LIBRARY_URL.'assets/css/sc-library-open-learning-v2-v4336.css',array(),SC_LIBRARY_VERSION);
        wp_register_script('sc-library-open-learning-v2-v4336',SC_LIBRARY_URL.'assets/js/sc-library-open-learning-v2-v4336.js',array(),SC_LIBRARY_VERSION,true);
    }
    public static function contract(){return array(
        'schema'=>self::SCHEMA,'open_course_finder_reused'=>true,'course_plan_meta_reused'=>self::COURSE_PLAN_META,'learning_route_meta'=>self::USER_META,
        'deterministic_course_ranking'=>true,'missing_course_metadata_remains_unknown'=>true,'course_page_is_current_authority'=>true,'provider_page_is_current_authority'=>true,
        'access_label_is_not_enrollment_guarantee'=>true,'certificate_label_is_not_credential_award'=>true,'saved_route_is_not_provider_enrollment'=>true,'saved_route_is_not_course_completion'=>true,
        'automatic_purchase'=>false,'automatic_enrollment'=>false,'automatic_completion'=>false,'automatic_certificate_claim'=>false,'automatic_workspace_write'=>false,'automatic_publication'=>false,'external_provider_credentials_stored'=>false,
    );}
    private static function now(){return gmdate('c');}
    private static function new_uuid(){return function_exists('wp_generate_uuid4')?wp_generate_uuid4():sprintf('%04x%04x-%04x-%04x-%04x-%04x%04x%04x',mt_rand(0,0xffff),mt_rand(0,0xffff),mt_rand(0,0xffff),mt_rand(0,0x0fff)|0x4000,mt_rand(0,0x3fff)|0x8000,mt_rand(0,0xffff),mt_rand(0,0xffff),mt_rand(0,0xffff));}
    private static function clean($v,$n=240){$v=sanitize_text_field((string)$v);return function_exists('mb_substr')?mb_substr($v,0,$n):substr($v,0,$n);}
    private static function clean_area($v,$n=3000){$v=sanitize_textarea_field((string)$v);return function_exists('mb_substr')?mb_substr($v,0,$n):substr($v,0,$n);}
    private static function catalog(){return class_exists('SC_Library_Open_Course_Finder')?SC_Library_Open_Course_Finder::launch_catalog():array();}
    private static function pathways(){return class_exists('SC_Library_Open_Course_Finder')?SC_Library_Open_Course_Finder::pathway_registry():array();}
    private static function providers(){return class_exists('SC_Library_Open_Course_Finder')?SC_Library_Open_Course_Finder::provider_registry():array();}
    private static function catalog_verified_on(){return class_exists('SC_Library_Open_Course_Finder')?SC_Library_Open_Course_Finder::VERIFIED_ON:'';}
    private static function course_index(){$out=array();foreach(self::catalog() as $c){$id=sanitize_key((string)($c['id']??''));if($id)$out[$id]=$c;}return $out;}
    private static function course_plan($uid){$uid=absint($uid);if(!$uid)return array();$p=get_user_meta($uid,self::COURSE_PLAN_META,true);return is_array($p)?$p:array();}
    private static function tokenize($v){$v=strtolower(wp_strip_all_tags((string)$v));$p=preg_split('/[^a-z0-9_-]+/',$v)?:array();return array_values(array_unique(array_filter($p,static fn($t)=>strlen($t)>=3)));}
    private static function stage_for_level($level){$level=strtolower(trim((string)$level));if(str_contains($level,'intro')||str_contains($level,'beginner'))return array('key'=>'foundation','label'=>'Foundation','rank'=>10);if(str_contains($level,'intermediate')||str_contains($level,'undergraduate'))return array('key'=>'development','label'=>'Development','rank'=>20);if(str_contains($level,'professional')||str_contains($level,'advanced'))return array('key'=>'applied','label'=>'Applied / advanced','rank'=>30);return array('key'=>'unspecified','label'=>'Level not sequenced','rank'=>40);}
    private static function access_score($access,$pref){$access=sanitize_key((string)$access);$open=array('free-open','free-course','free-certificate');$free=array_merge($open,array('free-audit','free-preview'));if('open-first'===$pref){if(in_array($access,$open,true))return 12;if(in_array($access,$free,true))return 4;return -8;}if('free-any'===$pref)return in_array($access,$free,true)?8:-8;return 0;}
    private static function access_allowed($access,$pref){$access=sanitize_key((string)$access);if('any'===$pref||'open-first'===$pref)return true;return in_array($access,array('free-open','free-course','free-certificate','free-audit','free-preview'),true);}

    public static function build_plan($args=array(),$uid=0){
        $topic=self::clean($args['topic']??$args['q']??'',180);$goal=self::clean_area($args['goal']??'',600);$pathway=sanitize_key((string)($args['pathway']??''));$access=sanitize_key((string)($args['access']??'open-first'));if(!isset(self::ACCESS_PREFERENCES[$access]))$access='open-first';$limit=min(6,max(1,absint($args['limit']??4)));$pathways=self::pathways();if($pathway&&!isset($pathways[$pathway]))$pathway='';$tokens=self::tokenize(trim($topic.' '.$goal));$learning=self::course_plan($uid);$providers=self::providers();$ranked=array();
        foreach(self::catalog() as $c){$id=sanitize_key((string)($c['id']??''));if(!$id||!self::access_allowed($c['access']??'',$access))continue;$hay=strtolower(implode(' ',array_merge(array((string)($c['title']??''),(string)($c['institution']??''),(string)($c['summary']??''),(string)($c['level']??''),(string)($c['prerequisites']??'')),(array)($c['subjects']??array()))));$score=self::access_score($c['access']??'',$access);$reasons=array();$matched=array();foreach($tokens as $t){if(str_contains($hay,$t)){$score+=str_contains(strtolower((string)($c['title']??'')),$t)?10:4;$matched[]=$t;}}$cp=array_values(array_filter(array_map('sanitize_key',(array)($c['pathways']??array()))));if($pathway&&in_array($pathway,$cp,true)){$score+=28;$reasons[]='selected-knowledge-pathway';}if(!$pathway&&$tokens){foreach($cp as $slug){$terms=strtolower((string)($pathways[$slug]['terms']??''));foreach($tokens as $t){if($terms&&str_contains($terms,$t))$score+=2;}}}if($matched)$reasons[]='course-metadata-match:'.implode(',',array_slice(array_unique($matched),0,5));if(!$tokens&&!$pathway){$score+=1;$reasons[]='general-learning-catalog';}if($score<1)continue;$stage=self::stage_for_level($c['level']??'');$pid=sanitize_key((string)($c['provider']??''));$p=$providers[$pid]??array();$ranked[]=array('course_id'=>$id,'title'=>self::clean($c['title']??'',240),'institution'=>self::clean($c['institution']??'',160),'provider'=>self::clean($p['name']??$pid,160),'url'=>esc_url_raw((string)($c['url']??'')),'subjects'=>array_values(array_map(static fn($v)=>self::clean($v,80),(array)($c['subjects']??array()))),'level'=>self::clean($c['level']??'',80),'stage'=>$stage['key'],'stage_label'=>$stage['label'],'stage_rank'=>$stage['rank'],'access'=>sanitize_key((string)($c['access']??'')),'access_label'=>self::clean($c['access_label']??'',100),'access_note'=>self::clean_area($c['access_note']??'',600),'duration_label'=>self::clean($c['duration_label']??'',100),'duration_known'=>''!==trim((string)($c['duration_label']??'')),'language'=>self::clean($c['language']??'',100),'prerequisites'=>self::clean_area($c['prerequisites']??'',600),'prerequisites_known'=>''!==trim((string)($c['prerequisites']??'')),'pace'=>self::clean($c['pace']??'',100),'credential'=>self::clean_area($c['credential']??'',600),'pathways'=>$cp,'my_learning_state'=>sanitize_key((string)($learning[$id]??'')),'score'=>$score,'rank_reasons'=>$reasons,'provider_current_terms_authoritative'=>true);
        }
        usort($ranked,static function($a,$b){$s=absint($b['score']??0)<=>absint($a['score']??0);if($s)return $s;$st=absint($a['stage_rank']??40)<=>absint($b['stage_rank']??40);return $st?:strcmp((string)($a['course_id']??''),(string)($b['course_id']??''));});$selected=array_slice($ranked,0,$limit);usort($selected,static function($a,$b){$st=absint($a['stage_rank']??40)<=>absint($b['stage_rank']??40);if($st)return $st;$s=absint($b['score']??0)<=>absint($a['score']??0);return $s?:strcmp((string)($a['course_id']??''),(string)($b['course_id']??''));});foreach($selected as $i=>&$c){$c['sequence']=$i+1;unset($c['stage_rank']);}unset($c);
        return array('schema'=>self::SCHEMA,'generated_at'=>self::now(),'catalog_verified_on'=>self::catalog_verified_on(),'query'=>array('topic'=>$topic,'goal'=>$goal,'pathway'=>$pathway,'access'=>$access,'limit'=>$limit),'courses'=>$selected,'candidate_count'=>count($ranked),'sequencing_basis'=>'declared-level-label-then-match-score','missing_prerequisites_mean'=>'not-recorded-not-none','missing_duration_mean'=>'not-recorded-not-zero','provider_terms_authoritative'=>true,'saved_route_is_not_enrollment'=>true,'automatic_completion'=>false);
    }

    private static function routes_for_user($uid){$uid=absint($uid);if(!$uid)return array();$r=get_user_meta($uid,self::USER_META,true);$r=is_array($r)?array_values(array_filter($r,'is_array')):array();return array_slice($r,-self::MAX_ROUTES);}
    private static function write_routes($uid,$r){$r=is_array($r)?array_values(array_filter($r,'is_array')):array();update_user_meta(absint($uid),self::USER_META,array_slice($r,-self::MAX_ROUTES));}
    private static function context_is_valid($uid,$project_id,$bundle_id,$notebook_id){$project_id=absint($project_id);$notebook_id=absint($notebook_id);$bundle_id=self::clean($bundle_id,100);if($project_id){if(!class_exists('SC_Library_Unified_Research_Projects_Source_Bundles')||!SC_Library_Unified_Research_Projects_Source_Bundles::user_owns_project($project_id,$uid))return false;if($bundle_id){$found=false;foreach(SC_Library_Unified_Research_Projects_Source_Bundles::bundles_for_project($project_id) as $b){if($bundle_id===(string)($b['bundle_id']??'')){$found=true;break;}}if(!$found)return false;}}elseif($bundle_id)return false;if($notebook_id){if(!class_exists('SC_Library_Reading_Notebook_Annotations')||!SC_Library_Reading_Notebook_Annotations::user_owns_notebook($notebook_id,$uid))return false;}return true;}
    private static function checksum($p){return hash('sha256',wp_json_encode($p,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE));}
    private static function sanitize_course_ids($ids){$idx=self::course_index();if(is_string($ids))$ids=preg_split('/[\s,]+/',$ids);$out=array();foreach((array)$ids as $id){$id=sanitize_key((string)$id);if($id&&isset($idx[$id])&&!in_array($id,$out,true))$out[]=$id;if(count($out)>=self::MAX_COURSES_PER_ROUTE)break;}return $out;}
    public static function route_manifest($route,$uid){if(!is_array($route))return array();$idx=self::course_index();$learning=self::course_plan($uid);$courses=array();foreach((array)($route['course_ids']??array()) as $id){$id=sanitize_key((string)$id);if(!isset($idx[$id]))continue;$c=$idx[$id];$courses[]=array('course_id'=>$id,'title'=>self::clean($c['title']??'',240),'institution'=>self::clean($c['institution']??'',160),'url'=>esc_url_raw((string)($c['url']??'')),'level'=>self::clean($c['level']??'',80),'access'=>sanitize_key((string)($c['access']??'')),'access_label'=>self::clean($c['access_label']??'',100),'my_learning_state'=>sanitize_key((string)($learning[$id]??'')));}$p=array('schema'=>self::MANIFEST_SCHEMA,'route_id'=>self::clean($route['route_id']??'',80),'route_urn'=>self::clean($route['route_urn']??'',120),'title'=>self::clean($route['title']??'',200),'goal'=>self::clean_area($route['goal']??'',1200),'pathway'=>sanitize_key((string)($route['pathway']??'')),'access_preference'=>sanitize_key((string)($route['access_preference']??'open-first')),'status'=>sanitize_key((string)($route['status']??'planned')),'project_id'=>absint($route['project_id']??0),'bundle_id'=>self::clean($route['bundle_id']??'',100),'notebook_id'=>absint($route['notebook_id']??0),'course_ids'=>array_values(array_map('sanitize_key',(array)($route['course_ids']??array()))),'courses'=>$courses,'catalog_verified_on'=>self::catalog_verified_on(),'created_at'=>self::clean($route['created_at']??'',60),'updated_at'=>self::clean($route['updated_at']??'',60),'references_only'=>true,'provider_terms_authoritative'=>true,'automatic_enrollment'=>false,'automatic_completion'=>false,'automatic_workspace_write'=>false);$p['manifest_sha256']=self::checksum($p);return $p;}
    public static function save_route($uid,$data){$uid=absint($uid);if(!$uid)return new WP_Error('sc_learning_auth','Sign in to save a learning route.',array('status'=>401));$ids=self::sanitize_course_ids($data['course_ids']??array());if(!$ids)return new WP_Error('sc_learning_courses','Choose at least one listed course.',array('status'=>400));$project=absint($data['project_id']??0);$bundle=self::clean($data['bundle_id']??'',100);$notebook=absint($data['notebook_id']??0);if(!self::context_is_valid($uid,$project,$bundle,$notebook))return new WP_Error('sc_learning_context','The selected research context is not available to this account.',array('status'=>403));$pathways=self::pathways();$path=sanitize_key((string)($data['pathway']??''));if($path&&!isset($pathways[$path]))$path='';$access=sanitize_key((string)($data['access_preference']??'open-first'));if(!isset(self::ACCESS_PREFERENCES[$access]))$access='open-first';$status=sanitize_key((string)($data['status']??'planned'));if(!isset(self::ROUTE_STATUSES[$status]))$status='planned';$uuid=self::new_uuid();$r=array('route_id'=>'learning-route-'.$uuid,'route_urn'=>'urn:sc:learning-route:'.$uuid,'title'=>self::clean($data['title']??'Learning route',200),'goal'=>self::clean_area($data['goal']??'',1200),'pathway'=>$path,'access_preference'=>$access,'status'=>$status,'course_ids'=>$ids,'project_id'=>$project,'bundle_id'=>$bundle,'notebook_id'=>$notebook,'notes'=>self::clean_area($data['notes']??'',3000),'created_at'=>self::now(),'updated_at'=>self::now());$routes=self::routes_for_user($uid);$routes[]=$r;self::write_routes($uid,$routes);return self::route_manifest($r,$uid);}
    public static function delete_route($uid,$id){$id=self::clean($id,80);$routes=self::routes_for_user($uid);$next=array_values(array_filter($routes,static fn($r)=>(string)($r['route_id']??'')!==$id));if(count($next)===count($routes))return new WP_Error('sc_learning_route','Learning route not found.',array('status'=>404));self::write_routes($uid,$next);return true;}

    public function register_rest_routes(){
        register_rest_route(self::REST_NAMESPACE,self::REST_ROUTE,array('methods'=>WP_REST_Server::READABLE,'permission_callback'=>'__return_true','callback'=>array($this,'rest_plan')));
        register_rest_route(self::REST_NAMESPACE,self::REST_ROUTE.'/routes',array(array('methods'=>WP_REST_Server::READABLE,'permission_callback'=>array($this,'rest_signed_in'),'callback'=>array($this,'rest_routes')),array('methods'=>WP_REST_Server::CREATABLE,'permission_callback'=>array($this,'rest_signed_in'),'callback'=>array($this,'rest_save_route'))));
        register_rest_route(self::REST_NAMESPACE,self::REST_ROUTE.'/routes/(?P<id>[a-zA-Z0-9-]+)',array('methods'=>WP_REST_Server::DELETABLE,'permission_callback'=>array($this,'rest_signed_in'),'callback'=>array($this,'rest_delete_route')));
    }
    public function rest_signed_in(){return is_user_logged_in();}
    public function rest_plan(WP_REST_Request $r){return rest_ensure_response(self::build_plan(array('topic'=>$r->get_param('topic')?:$r->get_param('q'),'goal'=>$r->get_param('goal'),'pathway'=>$r->get_param('pathway'),'access'=>$r->get_param('access'),'limit'=>$r->get_param('limit')),get_current_user_id()));}
    public function rest_routes(){$out=array();foreach(self::routes_for_user(get_current_user_id()) as $r)$out[]=self::route_manifest($r,get_current_user_id());return rest_ensure_response(array('schema'=>self::ROUTE_SCHEMA,'routes'=>$out,'count'=>count($out),'private'=>true));}
    public function rest_save_route(WP_REST_Request $r){$s=self::save_route(get_current_user_id(),(array)$r->get_json_params());return is_wp_error($s)?$s:rest_ensure_response($s);}
    public function rest_delete_route(WP_REST_Request $r){$d=self::delete_route(get_current_user_id(),$r['id']);return is_wp_error($d)?$d:rest_ensure_response(array('deleted'=>true,'route_id'=>self::clean($r['id'],80)));}
    public function filter_learning_plan($plan,$args){return self::build_plan(is_array($args)?$args:array(),get_current_user_id());}
    public function filter_route_manifest($manifest,$route,$uid){return self::route_manifest(is_array($route)?$route:array(),absint($uid));}
    private static function project_options($uid){$out=array();if(!class_exists('SC_Library_Unified_Research_Projects_Source_Bundles'))return $out;foreach(SC_Library_Unified_Research_Projects_Source_Bundles::projects_for_user($uid) as $id)$out[]=array('id'=>absint($id),'title'=>get_the_title($id)?:sprintf('Project %d',$id));return $out;}
    private static function notebook_options($uid){$out=array();if(!class_exists('SC_Library_Reading_Notebook_Annotations'))return $out;foreach(SC_Library_Reading_Notebook_Annotations::notebooks_for_user($uid) as $id)$out[]=array('id'=>absint($id),'title'=>get_the_title($id)?:sprintf('Notebook %d',$id));return $out;}

    public function shortcode($atts){$atts=shortcode_atts(array('title'=>__('Open Learning II','sustainable-catalyst-library')),$atts,'sc_open_learning_ii');wp_enqueue_style('sc-library-open-learning-v2-v4336');wp_enqueue_script('sc-library-open-learning-v2-v4336');$signed=is_user_logged_in();$uid=get_current_user_id();wp_localize_script('sc-library-open-learning-v2-v4336','scOpenLearningII',array('restRoot'=>esc_url_raw(rest_url(self::REST_NAMESPACE.self::REST_ROUTE)),'nonce'=>wp_create_nonce('wp_rest'),'signedIn'=>$signed,'loginUrl'=>wp_login_url((string)get_permalink()),'projects'=>$signed?self::project_options($uid):array(),'notebooks'=>$signed?self::notebook_options($uid):array(),'strings'=>array('planning'=>__('Building a learning route…','sustainable-catalyst-library'),'empty'=>__('No launch-catalog courses matched this route. Broaden the topic, pathway, or access preference.','sustainable-catalyst-library'),'saved'=>__('Learning route saved to your Sustainable Catalyst account.','sustainable-catalyst-library'),'saveError'=>__('The learning route could not be saved.','sustainable-catalyst-library'))));$pathways=self::pathways();ob_start();?>
<section class="sc-open-learning-v2" data-sc-open-learning-v2 data-signed-in="<?php echo $signed?'1':'0'; ?>">
<header class="sc-open-learning-v2__header"><p class="sc-open-learning-v2__kicker"><?php esc_html_e('Open Learning II','sustainable-catalyst-library'); ?></p><h3><?php echo esc_html($atts['title']); ?></h3><p><?php esc_html_e('Build a transparent sequence from the reviewed Open Course Finder catalog. Sequence is based on declared course level and metadata match—not an inferred prerequisite graph. Provider pages remain authoritative for current enrollment, cost, certificates, and availability.','sustainable-catalyst-library'); ?></p></header>
<form class="sc-open-learning-v2__form" data-sc-learning-plan-form><label><span><?php esc_html_e('Topic or learning goal','sustainable-catalyst-library'); ?></span><input type="search" name="topic" maxlength="180" placeholder="e.g. systems thinking, Python, sustainable development"></label><label><span><?php esc_html_e('Knowledge Pathway','sustainable-catalyst-library'); ?></span><select name="pathway"><option value=""><?php esc_html_e('Any pathway','sustainable-catalyst-library'); ?></option><?php foreach($pathways as $slug=>$p):?><option value="<?php echo esc_attr($slug); ?>"><?php echo esc_html($p['title']); ?></option><?php endforeach;?></select></label><label><span><?php esc_html_e('Access preference','sustainable-catalyst-library'); ?></span><select name="access"><?php foreach(self::ACCESS_PREFERENCES as $v=>$l):?><option value="<?php echo esc_attr($v); ?>"><?php echo esc_html($l); ?></option><?php endforeach;?></select></label><label><span><?php esc_html_e('Route length','sustainable-catalyst-library'); ?></span><select name="limit"><option value="3">3 courses</option><option value="4" selected>4 courses</option><option value="5">5 courses</option><option value="6">6 courses</option></select></label><button type="submit"><?php esc_html_e('Build Learning Route','sustainable-catalyst-library'); ?></button></form>
<div class="sc-open-learning-v2__truth" role="note"><strong><?php esc_html_e('What this route means','sustainable-catalyst-library'); ?></strong><span><?php esc_html_e('It is a Sustainable Catalyst planning aid built from reviewed course metadata. A blank prerequisite or duration means “not recorded,” not “none.” Saving a route does not enroll you or change your existing My Learning course statuses.','sustainable-catalyst-library'); ?></span></div><div class="sc-open-learning-v2__status" data-sc-learning-status aria-live="polite"></div><div class="sc-open-learning-v2__results" data-sc-learning-results></div>
<?php if($signed):?><div class="sc-open-learning-v2__saved" data-sc-learning-saved><div><strong><?php esc_html_e('Saved learning routes','sustainable-catalyst-library'); ?></strong><span><?php esc_html_e('Private to your account; course/provider records remain canonical in Open Course Finder.','sustainable-catalyst-library'); ?></span></div><div data-sc-learning-saved-list aria-live="polite"></div></div><?php else:?><p class="sc-open-learning-v2__signin"><a href="<?php echo esc_url(wp_login_url((string)get_permalink())); ?>"><?php esc_html_e('Sign in with your Sustainable Catalyst / Workspace account to save a learning route →','sustainable-catalyst-library'); ?></a></p><?php endif;?>
</section><?php return ob_get_clean();}
}
