<?php
/** Unified Personal Research Environment — v4.4.0. */
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class SC_Library_Unified_Personal_Research_Environment {
    public const VERSION='4.4.0'; public const SCHEMA='sc-library-unified-personal-research-environment/1.0'; public const REST_NAMESPACE='sc-library/v1'; public const REST_ROUTE='/personal-research-environment';
    public function __construct(){ add_action('wp_enqueue_scripts',[$this,'register_assets']); add_action('rest_api_init',[$this,'register_rest_routes']); add_shortcode('sc_personal_research_environment',[$this,'shortcode']); add_filter('sc_library_personal_research_environment_state',[$this,'filter_state'],10,3); }
    public function register_assets(){ wp_register_style('sc-library-personal-research-environment-v440',SC_LIBRARY_URL.'assets/css/sc-library-personal-research-environment-v440.css',[],SC_LIBRARY_VERSION); wp_register_script('sc-library-personal-research-environment-v440',SC_LIBRARY_URL.'assets/js/sc-library-personal-research-environment-v440.js',[],SC_LIBRARY_VERSION,true); }
    public static function contract(){ return ['schema'=>self::SCHEMA,'record_owner'=>'current-wordpress-user','visibility'=>'private','same_library_workspace_account'=>true,'composition_only'=>true,'canonical_stores_unchanged'=>true,'new_private_record_store'=>false,'new_project_store'=>false,'new_notebook_store'=>false,'new_evidence_store'=>false,'duplicate_private_content'=>false,'automatic_record_migration'=>false,'automatic_project_write'=>false,'automatic_notebook_write'=>false,'automatic_evidence_promotion'=>false,'automatic_workspace_write'=>false,'automatic_publication'=>false,'remote_synthesis_receives_private_context'=>false]; }
    public function register_rest_routes(){ register_rest_route(self::REST_NAMESPACE,self::REST_ROUTE,['methods'=>WP_REST_Server::READABLE,'permission_callback'=>[$this,'rest_signed_in'],'callback'=>[$this,'rest_state'],'args'=>['project_id'=>['sanitize_callback'=>'absint','default'=>0]]]); }
    public function rest_signed_in(){ return is_user_logged_in(); }
    public function rest_state(WP_REST_Request $r){ return rest_ensure_response(self::state_for_user(get_current_user_id(),absint($r->get_param('project_id')))); }
    private static function title($v,$fallback=''){ $v=sanitize_text_field((string)$v); return $v!==''?$v:$fallback; }
    private static function learning_routes($uid){ if(!class_exists('SC_Library_Open_Learning_II'))return []; $r=get_user_meta(absint($uid),SC_Library_Open_Learning_II::USER_META,true); return is_array($r)?array_slice(array_values(array_filter($r,'is_array')),-SC_Library_Open_Learning_II::MAX_ROUTES):[]; }
    private static function context_project_id($context){ return is_array($context)?absint($context['project_id']??0):0; }
    private static function recent(array $items){ usort($items,static fn($a,$b)=>strcmp((string)($b['updated_at']??''),(string)($a['updated_at']??''))); return array_slice($items,0,8); }
    public static function state_for_user($uid,$selected=0){
        $uid=absint($uid); if(!$uid)return new WP_Error('sc_research_home_signin',__('Sign in to open your personal research environment.','sustainable-catalyst-library'),['status'=>401]);
        $project_ids=class_exists('SC_Library_Unified_Research_Projects_Source_Bundles')?SC_Library_Unified_Research_Projects_Source_Bundles::projects_for_user($uid):[]; $projects=[]; $recent=[];
        foreach($project_ids as $pid){$s=SC_Library_Unified_Research_Projects_Source_Bundles::project_state($pid,$uid);if(is_wp_error($s))continue;$x=['project_id'=>absint($pid),'title'=>self::title($s['title']??'',sprintf(__('Project %d','sustainable-catalyst-library'),$pid)),'status'=>sanitize_key((string)($s['status']??'active')),'reference_count'=>absint($s['reference_count']??0),'bundle_count'=>absint($s['bundle_count']??0),'modified_gmt'=>(string)($s['modified_gmt']??''),'urn'=>(string)($s['project_identity']['urn']??'')];$projects[]=$x;$recent[]=['kind'=>'project','label'=>__('Research Project','sustainable-catalyst-library'),'title'=>$x['title'],'project_id'=>absint($pid),'updated_at'=>$x['modified_gmt'],'target'=>'#research-projects'];}
        $selected=absint($selected);$owned=array_map('absint',$project_ids);if($selected&&!in_array($selected,$owned,true))$selected=0;if(!$selected&&$projects)$selected=absint($projects[0]['project_id']);
        $items=class_exists('SC_Library_Personal_Collections_Recommendations')?SC_Library_Personal_Collections_Recommendations::items_for_user($uid):[];$collections=class_exists('SC_Library_Personal_Collections_Recommendations')?SC_Library_Personal_Collections_Recommendations::collections_for_user($uid):[];$continuity=class_exists('SC_Library_Saved_Searches_Watchlists_Queue')?SC_Library_Saved_Searches_Watchlists_Queue::state_for_user($uid):[];
        $notebooks=[];$nids=class_exists('SC_Library_Reading_Notebook_Annotations')?SC_Library_Reading_Notebook_Annotations::notebooks_for_user($uid):[];foreach($nids as $nid){$s=SC_Library_Reading_Notebook_Annotations::notebook_state($nid,$uid);if(is_wp_error($s))continue;$pid=self::context_project_id($s['project_context']??[]);$x=['notebook_id'=>absint($nid),'title'=>self::title($s['title']??'',__('Reading notebook','sustainable-catalyst-library')),'project_id'=>$pid,'note_count'=>absint($s['note_count']??0),'annotation_count'=>absint($s['annotation_count']??0),'updated_at'=>(string)($s['updated_at']??''),'urn'=>(string)($s['urn']??'')];$notebooks[]=$x;$recent[]=['kind'=>'notebook','label'=>__('Reading Notebook','sustainable-catalyst-library'),'title'=>$x['title'],'project_id'=>$pid,'updated_at'=>$x['updated_at'],'target'=>'#reading-notebooks'];}
        $matrices=[];$mids=class_exists('SC_Library_Evidence_Matrix_Claim_Intelligence')?SC_Library_Evidence_Matrix_Claim_Intelligence::matrices_for_user($uid):[];foreach($mids as $mid){$s=SC_Library_Evidence_Matrix_Claim_Intelligence::matrix_state($mid,$uid);if(is_wp_error($s))continue;$pid=self::context_project_id($s['project_context']??[]);$x=['matrix_id'=>absint($mid),'title'=>self::title($s['title']??'',__('Evidence matrix','sustainable-catalyst-library')),'project_id'=>$pid,'claim_count'=>absint($s['claim_count']??0),'evidence_link_count'=>absint($s['evidence_link_count']??0),'updated_at'=>(string)($s['updated_at']??''),'urn'=>(string)($s['urn']??'')];$matrices[]=$x;$recent[]=['kind'=>'matrix','label'=>__('Evidence Matrix','sustainable-catalyst-library'),'title'=>$x['title'],'project_id'=>$pid,'updated_at'=>$x['updated_at'],'target'=>'#evidence-matrix'];}
        $routes=self::learning_routes($uid);foreach($routes as $r){$recent[]=['kind'=>'learning_route','label'=>__('Learning Route','sustainable-catalyst-library'),'title'=>self::title($r['title']??'',__('Learning route','sustainable-catalyst-library')),'project_id'=>absint($r['project_id']??0),'updated_at'=>(string)($r['updated_at']??$r['created_at']??''),'target'=>'#open-learning-ii'];}
        $project=null;if($selected&&class_exists('SC_Library_Unified_Research_Projects_Source_Bundles')){$s=SC_Library_Unified_Research_Projects_Source_Bundles::project_state($selected,$uid);if(!is_wp_error($s)){$project=['project_id'=>$selected,'title'=>self::title($s['title']??'',__('Research project','sustainable-catalyst-library')),'status'=>sanitize_key((string)($s['status']??'active')),'research_question'=>sanitize_textarea_field((string)($s['research_question']??'')),'reference_count'=>absint($s['reference_count']??0),'bundle_count'=>absint($s['bundle_count']??0),'urn'=>(string)($s['project_identity']['urn']??''),'notebooks'=>array_values(array_filter($notebooks,static fn($n)=>absint($n['project_id']??0)===$selected)),'matrices'=>array_values(array_filter($matrices,static fn($m)=>absint($m['project_id']??0)===$selected)),'learning_routes'=>array_values(array_filter($routes,static fn($r)=>absint($r['project_id']??0)===$selected))];$project['notebook_count']=count($project['notebooks']);$project['matrix_count']=count($project['matrices']);$project['learning_route_count']=count($project['learning_routes']);}}
        $out=['schema'=>self::SCHEMA,'version'=>self::VERSION,'visibility'=>'private','user_id'=>$uid,'generated_at'=>gmdate('c'),'counts'=>['projects'=>count($projects),'personal_items'=>count($items),'personal_collections'=>count($collections),'saved_searches'=>count((array)($continuity['saved_searches']??[])),'watchlists'=>count((array)($continuity['watchlists']??[])),'research_queue'=>count((array)($continuity['research_queue']??[])),'reading_notebooks'=>count($notebooks),'evidence_matrices'=>count($matrices),'learning_routes'=>count($routes)],'projects'=>$projects,'selected_project_id'=>$selected,'selected_project'=>$project,'recent_activity'=>self::recent($recent),'contract'=>self::contract()];return apply_filters('sc_library_personal_research_environment_state_payload',$out,$uid,$selected);
    }
    public function filter_state($state,$uid,$project_id=0){$x=self::state_for_user(absint($uid),absint($project_id));return is_wp_error($x)?$state:$x;}
    private static function canonical(){return class_exists('SC_Library_Canonical_Route_Identity')?SC_Library_Canonical_Route_Identity::canonical_url():home_url('/knowledge-libraries/');}
    private static function project_url($pid,$fragment){return add_query_arg('sc_project',absint($pid),self::canonical()).$fragment;}
    public function shortcode($atts){
        $atts=shortcode_atts(['title'=>__('Unified Personal Research Environment','sustainable-catalyst-library')],$atts,'sc_personal_research_environment');wp_enqueue_style('sc-library-personal-research-environment-v440');wp_enqueue_script('sc-library-personal-research-environment-v440');
        $signed=is_user_logged_in();$selected=$signed?absint($_GET['sc_project']??0):0;$state=$signed?self::state_for_user(get_current_user_id(),$selected):null;$canonical=self::canonical();ob_start(); ?>
<section class="sc-personal-research-home" data-sc-personal-research-home="v4.4.0">
<header class="sc-personal-research-home__hero"><div><p><?php esc_html_e('One account · one private research home','sustainable-catalyst-library'); ?></p><h3><?php echo esc_html($atts['title']); ?></h3><span><?php esc_html_e('Resume projects, collections, saved research, notebooks, evidence work, learning routes, Workspace handoffs, and preservation from one account-scoped view without moving those records into a new database.','sustainable-catalyst-library'); ?></span></div><aside><strong><?php esc_html_e('Composition, not migration','sustainable-catalyst-library'); ?></strong><span><?php esc_html_e('Every underlying tool keeps its existing identity, permissions, provenance, and storage contract.','sustainable-catalyst-library'); ?></span></aside></header>
<?php if(!$signed||is_wp_error($state)): ?><div class="sc-personal-research-home__signin"><strong><?php esc_html_e('Sign in to open your private research home.','sustainable-catalyst-library'); ?></strong><a href="<?php echo esc_url(wp_login_url($canonical.'#personal-research-environment')); ?>"><?php esc_html_e('Sign in →','sustainable-catalyst-library'); ?></a></div>
<?php else:$counts=(array)($state['counts']??[]);$projects=(array)($state['projects']??[]);$project=is_array($state['selected_project']??null)?$state['selected_project']:null;$metrics=['projects'=>__('Projects','sustainable-catalyst-library'),'personal_items'=>__('My Library','sustainable-catalyst-library'),'saved_searches'=>__('Saved searches','sustainable-catalyst-library'),'watchlists'=>__('Watchlists','sustainable-catalyst-library'),'research_queue'=>__('Research queue','sustainable-catalyst-library'),'reading_notebooks'=>__('Notebooks','sustainable-catalyst-library'),'evidence_matrices'=>__('Evidence matrices','sustainable-catalyst-library'),'learning_routes'=>__('Learning routes','sustainable-catalyst-library')]; ?>
<div class="sc-personal-research-home__metrics" aria-label="<?php esc_attr_e('Private research totals','sustainable-catalyst-library'); ?>"><?php foreach($metrics as $key=>$label): ?><article><strong><?php echo esc_html((string)absint($counts[$key]??0)); ?></strong><span><?php echo esc_html($label); ?></span></article><?php endforeach; ?></div>
<?php if($projects): ?><form class="sc-personal-research-home__project-form" method="get" action="<?php echo esc_url($canonical); ?>" data-sc-personal-research-project-form><label><span><?php esc_html_e('Project context','sustainable-catalyst-library'); ?></span><select name="sc_project" data-sc-personal-research-project-select><?php foreach($projects as $item): ?><option value="<?php echo esc_attr((string)absint($item['project_id']??0)); ?>" <?php selected(absint($state['selected_project_id']??0),absint($item['project_id']??0)); ?>><?php echo esc_html((string)($item['title']??'')); ?></option><?php endforeach; ?></select></label><button type="submit"><?php esc_html_e('Open project home','sustainable-catalyst-library'); ?></button></form><?php endif; ?>
<?php if($project): ?><div class="sc-personal-research-home__project"><div><p class="sc-personal-research-home__eyebrow"><?php esc_html_e('Current research context','sustainable-catalyst-library'); ?></p><h4><?php echo esc_html((string)$project['title']); ?></h4><?php if(!empty($project['research_question'])):?><p><?php echo esc_html((string)$project['research_question']); ?></p><?php endif; ?><?php if(!empty($project['urn'])):?><code><?php echo esc_html((string)$project['urn']); ?></code><?php endif; ?></div><dl><div><dt><?php esc_html_e('References','sustainable-catalyst-library'); ?></dt><dd><?php echo esc_html((string)absint($project['reference_count']??0)); ?></dd></div><div><dt><?php esc_html_e('Source bundles','sustainable-catalyst-library'); ?></dt><dd><?php echo esc_html((string)absint($project['bundle_count']??0)); ?></dd></div><div><dt><?php esc_html_e('Notebooks','sustainable-catalyst-library'); ?></dt><dd><?php echo esc_html((string)absint($project['notebook_count']??0)); ?></dd></div><div><dt><?php esc_html_e('Evidence matrices','sustainable-catalyst-library'); ?></dt><dd><?php echo esc_html((string)absint($project['matrix_count']??0)); ?></dd></div><div><dt><?php esc_html_e('Learning routes','sustainable-catalyst-library'); ?></dt><dd><?php echo esc_html((string)absint($project['learning_route_count']??0)); ?></dd></div></dl></div><?php endif; ?>
<nav class="sc-personal-research-home__actions" aria-label="<?php esc_attr_e('Research environment actions','sustainable-catalyst-library'); ?>"><a href="#personal-library"><?php esc_html_e('My Library','sustainable-catalyst-library'); ?></a><a href="#saved-research"><?php esc_html_e('Saved Research','sustainable-catalyst-library'); ?></a><a href="#research-projects"><?php esc_html_e('Projects & Bundles','sustainable-catalyst-library'); ?></a><a href="#reading-notebooks"><?php esc_html_e('Reading Notebooks','sustainable-catalyst-library'); ?></a><a href="#evidence-matrix"><?php esc_html_e('Evidence Matrix','sustainable-catalyst-library'); ?></a><a href="#research-librarian"><?php esc_html_e('Research Librarian II','sustainable-catalyst-library'); ?></a><a href="#workspace-continuity"><?php esc_html_e('Continue in Workspace','sustainable-catalyst-library'); ?></a><a href="#research-portability"><?php esc_html_e('Export / Preserve','sustainable-catalyst-library'); ?></a></nav>
<?php if(!empty($state['recent_activity'])): ?><div class="sc-personal-research-home__recent"><h4><?php esc_html_e('Resume recent research','sustainable-catalyst-library'); ?></h4><div><?php foreach((array)$state['recent_activity'] as $item):$pid=absint($item['project_id']??0);$target=sanitize_text_field((string)($item['target']??'#research-projects'));$url=$pid?self::project_url($pid,$target):$target; ?><a href="<?php echo esc_url($url); ?>"><span><?php echo esc_html((string)($item['label']??__('Research','sustainable-catalyst-library'))); ?></span><strong><?php echo esc_html((string)($item['title']??'')); ?></strong><?php if(!empty($item['updated_at'])):?><small><?php echo esc_html((string)$item['updated_at']); ?></small><?php endif; ?></a><?php endforeach; ?></div></div><?php endif; ?>
<p class="sc-personal-research-home__boundary"><?php esc_html_e('This home summarizes records already owned by your Sustainable Catalyst account. It does not copy their private contents, create a replacement project model, publish anything, promote evidence, or write into Workspace automatically.','sustainable-catalyst-library'); ?></p>
<?php endif; ?></section><?php return (string)ob_get_clean();
    }
}
