<?php
/**
 * Evidence Matrix & Claim Intelligence — v4.3.32.
 *
 * Adds a private, account-owned project matrix for explicit claim/evidence
 * relationships. It reuses canonical Research Projects, Reading Notebooks,
 * v2.7 Evidence Notes/Research Claims, and source references without copying
 * underlying Library records or silently promoting notes into evidence.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }

final class SC_Library_Evidence_Matrix_Claim_Intelligence {
    public const VERSION = '4.3.32';
    public const SCHEMA = 'sc-library-evidence-matrix/1.0';
    public const CLAIM_SCHEMA = 'sc-library-matrix-claim/1.0';
    public const LINK_SCHEMA = 'sc-library-matrix-evidence-link/1.0';
    public const DIAGNOSTIC_SCHEMA = 'sc-library-claim-intelligence-diagnostics/1.0';
    public const POST_TYPE = 'sc_evidence_matrix';
    public const REST_NAMESPACE = 'sc-library/v1';
    public const REST_ROUTE = '/evidence-matrices';
    public const NONCE_ACTION = 'sc_library_evidence_matrix_v4332';

    public const META_UUID = '_sc_evidence_matrix_uuid_v4332';
    public const META_PROJECT_ID = '_sc_evidence_matrix_project_id_v4332';
    public const META_BUNDLE_ID = '_sc_evidence_matrix_bundle_id_v4332';
    public const META_STATUS = '_sc_evidence_matrix_status_v4332';
    public const META_CLAIMS = '_sc_evidence_matrix_claims_v4332';
    public const META_LINKS = '_sc_evidence_matrix_links_v4332';
    public const META_UPDATED_AT = '_sc_evidence_matrix_updated_at_v4332';

    public const MAX_MATRICES_PER_USER = 40;
    public const MAX_CLAIMS_PER_MATRIX = 120;
    public const MAX_LINKS_PER_MATRIX = 600;
    public const MAX_EXCERPT_CHARS = 4000;
    public const MAX_TAGS = 20;

    private const MATRIX_STATUSES = array('active'=>'Active','review'=>'In review','complete'=>'Complete','archived'=>'Archived');
    private const CLAIM_STATUSES = array('working'=>'Working','review'=>'Review','supported'=>'Supported (user assessment)','mixed'=>'Mixed (user assessment)','contradicted'=>'Contradicted (user assessment)','unresolved'=>'Unresolved','retired'=>'Retired');
    private const CONFIDENCE = array('unset'=>'Not set','low'=>'Low','medium'=>'Medium','high'=>'High');
    private const RELATIONS = array('supports'=>'Supports','qualifies'=>'Qualifies','contradicts'=>'Contradicts','contextualizes'=>'Contextualizes','unresolved'=>'Unresolved / follow-up');
    private const SOURCE_KINDS = array('reading_note'=>'Reading note / excerpt','source_annotation'=>'Source annotation','canonical_evidence'=>'Canonical v2.7 Evidence Note','project_reference'=>'Project source/reference','external'=>'External source');
    private const LOCATOR_TYPES = array('page'=>'Page','section'=>'Section / heading','timestamp'=>'Timestamp','paragraph'=>'Paragraph / passage','dataset'=>'Dataset location','custom'=>'Custom');

    public function __construct() {
        add_action('init',array($this,'register_post_type'),12);
        add_action('wp_enqueue_scripts',array($this,'register_assets'));
        add_action('rest_api_init',array($this,'register_rest_routes'));
        add_shortcode('sc_evidence_matrix_workspace',array($this,'shortcode'));
        add_action('wp_ajax_sc_library_v4332_create_matrix',array($this,'ajax_create_matrix'));
        add_action('wp_ajax_sc_library_v4332_update_matrix',array($this,'ajax_update_matrix'));
        add_action('wp_ajax_sc_library_v4332_delete_matrix',array($this,'ajax_delete_matrix'));
        add_action('wp_ajax_sc_library_v4332_add_claim',array($this,'ajax_add_claim'));
        add_action('wp_ajax_sc_library_v4332_update_claim',array($this,'ajax_update_claim'));
        add_action('wp_ajax_sc_library_v4332_delete_claim',array($this,'ajax_delete_claim'));
        add_action('wp_ajax_sc_library_v4332_add_link',array($this,'ajax_add_link'));
        add_action('wp_ajax_sc_library_v4332_update_link',array($this,'ajax_update_link'));
        add_action('wp_ajax_sc_library_v4332_delete_link',array($this,'ajax_delete_link'));
        add_filter('sc_library_evidence_matrix_state',array($this,'filter_matrix_state'),10,3);
        add_filter('sc_library_evidence_matrix_manifest',array($this,'filter_matrix_manifest'),10,3);
        add_action('sc_library_create_matrix_claim',array($this,'action_create_claim'),10,3);
        add_action('sc_library_link_matrix_evidence',array($this,'action_link_evidence'),10,3);
    }

    public function register_post_type() {
        register_post_type(self::POST_TYPE,array(
            'labels'=>array('name'=>__('Evidence Matrices','sustainable-catalyst-library'),'singular_name'=>__('Evidence Matrix','sustainable-catalyst-library')),
            'public'=>false,'publicly_queryable'=>false,'show_ui'=>false,'show_in_menu'=>false,'show_in_rest'=>false,'exclude_from_search'=>true,'rewrite'=>false,'query_var'=>false,
            'supports'=>array('title','author'),'capability_type'=>'post','map_meta_cap'=>true,
        ));
    }

    public function register_assets() {
        wp_register_style('sc-library-evidence-matrix-v4332',SC_LIBRARY_URL.'assets/css/sc-library-evidence-matrix-v4332.css',array(),SC_LIBRARY_VERSION);
        wp_register_script('sc-library-evidence-matrix-v4332',SC_LIBRARY_URL.'assets/js/sc-library-evidence-matrix-v4332.js',array(),SC_LIBRARY_VERSION,true);
    }

    public static function contract() {
        return array(
            'schema'=>self::SCHEMA,'record_owner'=>'wordpress-post-author','visibility'=>'private-by-default','same_library_workspace_account'=>true,
            'canonical_project_reuse'=>true,'canonical_v270_evidence_preserved'=>true,'source_links_are_references'=>true,'copy_underlying_source_records'=>false,'copy_private_binary_files'=>false,
            'explicit_evidence_promotion_only'=>true,'automatic_evidence_promotion'=>false,'automatic_claim_generation'=>false,'automatic_claim_status_change'=>false,'automatic_confidence_scoring'=>false,
            'deterministic_diagnostics_only'=>true,'diagnostics_are_not_conclusions'=>true,'automatic_publication'=>false,'automatic_workspace_write'=>false,
        );
    }
    private static function now(){return gmdate('c');}
    private static function new_uuid(){return function_exists('wp_generate_uuid4')?wp_generate_uuid4():sprintf('%04x%04x-%04x-%04x-%04x-%04x%04x%04x',mt_rand(0,0xffff),mt_rand(0,0xffff),mt_rand(0,0xffff),mt_rand(0,0x0fff)|0x4000,mt_rand(0,0x3fff)|0x8000,mt_rand(0,0xffff),mt_rand(0,0xffff),mt_rand(0,0xffff));}
    private static function clean_text($v,$n=240){$v=sanitize_text_field((string)$v);return function_exists('mb_substr')?mb_substr($v,0,$n):substr($v,0,$n);}
    private static function clean_area($v,$n=12000){$v=sanitize_textarea_field((string)$v);return function_exists('mb_substr')?mb_substr($v,0,$n):substr($v,0,$n);}
    private static function enum_value($v,$allowed,$fallback){$v=sanitize_key((string)$v);return array_key_exists($v,$allowed)?$v:$fallback;}
    private static function tags($v){if(is_string($v)){$v=preg_split('/[,\n]+/',$v);} $out=array();foreach((array)$v as $t){$t=self::clean_text($t,60);if($t!==''&&!in_array($t,$out,true))$out[]=$t;if(count($out)>=self::MAX_TAGS)break;}return $out;}
    private static function array_meta($id,$key,$limit){$v=get_post_meta(absint($id),$key,true);$v=is_array($v)?array_values(array_filter($v,'is_array')):array();return array_slice($v,-absint($limit));}
    private static function write_array_meta($id,$key,$v,$limit){$v=is_array($v)?array_values(array_filter($v,'is_array')):array();update_post_meta(absint($id),$key,array_slice($v,-absint($limit)));update_post_meta(absint($id),self::META_UPDATED_AT,self::now());}

    public static function user_owns_matrix($matrix_id,$user_id){$p=get_post(absint($matrix_id));return $p instanceof WP_Post&&self::POST_TYPE===$p->post_type&&absint($p->post_author)===absint($user_id)&&absint($user_id)>0;}
    public static function matrices_for_user($user_id){$ids=get_posts(array('post_type'=>self::POST_TYPE,'post_status'=>array('private','draft','publish','pending'),'author'=>absint($user_id),'posts_per_page'=>self::MAX_MATRICES_PER_USER,'orderby'=>'modified','order'=>'DESC','fields'=>'ids'));return array_values(array_map('absint',$ids));}
    private static function context_valid($user_id,$project_id,$bundle_id=''){
        $project_id=absint($project_id);$bundle_id=self::clean_text($bundle_id,80);if(!$project_id)return $bundle_id==='';
        if(!class_exists('SC_Library_Unified_Research_Projects_Source_Bundles')||!SC_Library_Unified_Research_Projects_Source_Bundles::user_owns_project($project_id,$user_id))return false;
        if($bundle_id==='')return true;foreach(SC_Library_Unified_Research_Projects_Source_Bundles::bundles_for_project($project_id) as $b){if((string)($b['bundle_id']??'')===$bundle_id)return true;}return false;
    }
    private static function context($matrix_id,$user_id){$pid=absint(get_post_meta($matrix_id,self::META_PROJECT_ID,true));$bid=self::clean_text(get_post_meta($matrix_id,self::META_BUNDLE_ID,true),80);$valid=self::context_valid($user_id,$pid,$bid);$out=array('project_id'=>$pid,'bundle_id'=>$bid,'valid'=>$valid,'project_title'=>'','bundle_title'=>'');if($valid&&$pid){$out['project_title']=get_the_title($pid)?:'';if($bid&&class_exists('SC_Library_Unified_Research_Projects_Source_Bundles'))foreach(SC_Library_Unified_Research_Projects_Source_Bundles::bundles_for_project($pid) as $b){if(($b['bundle_id']??'')===$bid){$out['bundle_title']=$b['title']??'';break;}}}return $out;}

    private static function sanitize_claim($in,$gen=true){$in=is_array($in)?$in:array();$id=self::clean_text($in['id']??'',80);if($gen&&$id==='')$id=self::new_uuid();return array(
        'schema'=>self::CLAIM_SCHEMA,'id'=>$id,'urn'=>$id?'urn:sc:matrix-claim:'.$id:'','title'=>self::clean_text($in['title']??'',180),'statement'=>self::clean_area($in['statement']??'',6000),
        'status'=>self::enum_value($in['status']??'',self::CLAIM_STATUSES,'working'),'confidence'=>self::enum_value($in['confidence']??'',self::CONFIDENCE,'unset'),
        'scope'=>self::clean_area($in['scope']??'',3000),'assumptions'=>self::clean_area($in['assumptions']??'',3000),'limitations'=>self::clean_area($in['limitations']??'',3000),'counterclaim'=>self::clean_area($in['counterclaim']??'',3000),
        'tags'=>self::tags($in['tags']??array()),'position'=>max(0,min(9999,absint($in['position']??0))),'canonical_claim_id'=>absint($in['canonical_claim_id']??0),
        'created_at'=>self::clean_text($in['created_at']??'',40),'created_by'=>absint($in['created_by']??0),'updated_at'=>self::clean_text($in['updated_at']??'',40),
    );}
    private static function sanitize_link($in,$gen=true){$in=is_array($in)?$in:array();$id=self::clean_text($in['id']??'',80);if($gen&&$id==='')$id=self::new_uuid();$excerpt=self::clean_area($in['excerpt']??'',self::MAX_EXCERPT_CHARS);return array(
        'schema'=>self::LINK_SCHEMA,'id'=>$id,'urn'=>$id?'urn:sc:matrix-evidence-link:'.$id:'','claim_id'=>self::clean_text($in['claim_id']??'',80),'relation'=>self::enum_value($in['relation']??'',self::RELATIONS,'supports'),
        'source_kind'=>self::enum_value($in['source_kind']??'',self::SOURCE_KINDS,'external'),'source_ref'=>self::clean_text($in['source_ref']??'',360),'source_label'=>self::clean_text($in['source_label']??'',220),'source_url'=>esc_url_raw((string)($in['source_url']??'')),
        'source_key'=>self::clean_text($in['source_key']??'',420),'locator_type'=>self::enum_value($in['locator_type']??'',self::LOCATOR_TYPES,'custom'),'locator_value'=>self::clean_text($in['locator_value']??'',180),'excerpt'=>$excerpt,'rationale'=>self::clean_area($in['rationale']??'',5000),
        'quote_checked'=>!empty($in['quote_checked']),'locator_checked'=>!empty($in['locator_checked']),'canonical_evidence_id'=>absint($in['canonical_evidence_id']??0),
        'created_at'=>self::clean_text($in['created_at']??'',40),'created_by'=>absint($in['created_by']??0),'updated_at'=>self::clean_text($in['updated_at']??'',40),
    );}
    public static function claims_for_matrix($matrix_id){$out=array();foreach(self::array_meta($matrix_id,self::META_CLAIMS,self::MAX_CLAIMS_PER_MATRIX) as $raw){$x=self::sanitize_claim($raw,false);if($x['id'])$out[]=$x;}usort($out,static fn($a,$b)=>($a['position']<=>$b['position'])?:strcmp($a['created_at'],$b['created_at']));return $out;}
    public static function links_for_matrix($matrix_id){$out=array();foreach(self::array_meta($matrix_id,self::META_LINKS,self::MAX_LINKS_PER_MATRIX) as $raw){$x=self::sanitize_link($raw,false);if($x['id'])$out[]=$x;}return $out;}

    private static function find_reading_record($user_id,$kind,$source_ref){
        if(!class_exists('SC_Library_Reading_Notebook_Annotations'))return array();$parts=explode(':',(string)$source_ref,2);$nid=absint($parts[0]??0);$rid=self::clean_text($parts[1]??'',80);if(!$nid||!$rid||!SC_Library_Reading_Notebook_Annotations::user_owns_notebook($nid,$user_id))return array();
        $state=SC_Library_Reading_Notebook_Annotations::notebook_state($nid,$user_id);if(is_wp_error($state))return array();$bucket=$kind==='reading_note'?'notes':'annotations';foreach((array)($state[$bucket]??array()) as $r){if(($r['id']??'')===$rid){$res=(array)($r['source_resolution']??array());$label=(string)($res['label']??($r['source_label']??($r['title']??get_the_title($nid))));$url=(string)($res['url']??($r['source_url']??''));$sourcekey=(string)($res['family']??($r['source_family']??'external')).':'.(string)($res['ref_id']??($r['source_ref_id']??''));if(trim($sourcekey,':')==='external')$sourcekey='external:'.($url?:$label);return array('resolved'=>true,'label'=>$label,'url'=>$url,'source_key'=>$sourcekey,'excerpt'=>(string)($r['excerpt']??''),'locator_type'=>(string)($r['locator_type']??'custom'),'locator_value'=>(string)($r['locator_value']??''),'notebook_id'=>$nid,'record'=>$r);}}return array();
    }
    private static function resolve_link_source($user_id,$link){
        $kind=$link['source_kind'];$ref=$link['source_ref'];
        if(in_array($kind,array('reading_note','source_annotation'),true)){$r=self::find_reading_record($user_id,$kind,$ref);if($r)return $r;}
        if($kind==='canonical_evidence'&&class_exists('SC_Library_Evidence_Claim_Linking')){$id=absint($ref?:$link['canonical_evidence_id']);if($id){$data=SC_Library_Evidence_Claim_Linking::get_evidence_data($id,true);if($data)return array('resolved'=>true,'label'=>$data['title']??'Evidence Note','url'=>$data['source_url']??'','source_key'=>'canonical-evidence:'.$id,'excerpt'=>$data['content']??'','locator_type'=>$data['locator_type']??'custom','locator_value'=>$data['locator_label']?:($data['locator_start']??''),'canonical_evidence'=>$data);}}
        if($kind==='project_reference'&&class_exists('SC_Library_Unified_Research_Projects_Source_Bundles')){$parts=explode(':',$ref,2);$family=$parts[0]??'external';$rid=$parts[1]??'';$r=SC_Library_Unified_Research_Projects_Source_Bundles::resolve_reference($user_id,$family,$rid,$link['source_url'],$link['source_label']);return array('resolved'=>!empty($r['resolved']),'label'=>$r['label']??$link['source_label'],'url'=>$r['url']??$link['source_url'],'source_key'=>$family.':'.$rid,'resolution'=>$r);}
        if($kind==='external'&&($link['source_url']||$link['source_label']))return array('resolved'=>true,'label'=>$link['source_label'],'url'=>$link['source_url'],'source_key'=>'external:'.($link['source_url']?:$link['source_label']));
        return array('resolved'=>false,'label'=>$link['source_label'],'url'=>$link['source_url'],'source_key'=>$link['source_key'],'status'=>'unresolved');
    }
    private static function enrich_link($user_id,$link){$r=self::resolve_link_source($user_id,$link);$link['resolution']=$r;if(!$link['source_label']&&!empty($r['label']))$link['source_label']=$r['label'];if(!$link['source_url']&&!empty($r['url']))$link['source_url']=$r['url'];if(!$link['source_key']&&!empty($r['source_key']))$link['source_key']=$r['source_key'];if(!$link['excerpt']&&!empty($r['excerpt']))$link['excerpt']=self::clean_area($r['excerpt'],self::MAX_EXCERPT_CHARS);if(($link['locator_type']==='custom'||!$link['locator_type'])&&!empty($r['locator_type']))$link['locator_type']=self::enum_value($r['locator_type'],self::LOCATOR_TYPES,'custom');if(!$link['locator_value']&&!empty($r['locator_value']))$link['locator_value']=self::clean_text($r['locator_value'],180);return $link;}

    public static function create_matrix_for_user($user_id,$in){$user_id=absint($user_id);if(!$user_id)return new WP_Error('sc_matrix_signin',__('Sign in to create an evidence matrix.','sustainable-catalyst-library'));if(count(self::matrices_for_user($user_id))>=self::MAX_MATRICES_PER_USER)return new WP_Error('sc_matrix_limit',__('The private evidence-matrix limit has been reached.','sustainable-catalyst-library'));$title=self::clean_text($in['title']??'',180);if(!$title)return new WP_Error('sc_matrix_title',__('Enter an evidence-matrix title.','sustainable-catalyst-library'));$pid=absint($in['project_id']??0);$bid=self::clean_text($in['bundle_id']??'',80);if(!self::context_valid($user_id,$pid,$bid))return new WP_Error('sc_matrix_context',__('Choose a Research Project or Source Bundle owned by this account.','sustainable-catalyst-library'));$id=wp_insert_post(array('post_type'=>self::POST_TYPE,'post_status'=>'private','post_title'=>$title,'post_author'=>$user_id),true);if(is_wp_error($id))return $id;update_post_meta($id,self::META_UUID,self::new_uuid());update_post_meta($id,self::META_PROJECT_ID,$pid);update_post_meta($id,self::META_BUNDLE_ID,$bid);update_post_meta($id,self::META_STATUS,'active');update_post_meta($id,self::META_CLAIMS,array());update_post_meta($id,self::META_LINKS,array());update_post_meta($id,self::META_UPDATED_AT,self::now());do_action('sc_library_evidence_matrix_created',$id,$user_id);return self::matrix_state($id,$user_id);}
    public static function update_matrix_for_user($user_id,$id,$in){if(!self::user_owns_matrix($id,$user_id))return new WP_Error('sc_matrix_forbidden',__('That evidence matrix is not available to this account.','sustainable-catalyst-library'),array('status'=>403));$u=array('ID'=>absint($id));if(array_key_exists('title',$in))$u['post_title']=self::clean_text($in['title'],180);if(count($u)>1)wp_update_post($u);$pid=array_key_exists('project_id',$in)?absint($in['project_id']):absint(get_post_meta($id,self::META_PROJECT_ID,true));$bid=array_key_exists('bundle_id',$in)?self::clean_text($in['bundle_id'],80):self::clean_text(get_post_meta($id,self::META_BUNDLE_ID,true),80);if(!self::context_valid($user_id,$pid,$bid))return new WP_Error('sc_matrix_context',__('Choose a Research Project or Source Bundle owned by this account.','sustainable-catalyst-library'));update_post_meta($id,self::META_PROJECT_ID,$pid);update_post_meta($id,self::META_BUNDLE_ID,$bid);if(array_key_exists('status',$in))update_post_meta($id,self::META_STATUS,self::enum_value($in['status'],self::MATRIX_STATUSES,'active'));update_post_meta($id,self::META_UPDATED_AT,self::now());return self::matrix_state($id,$user_id);}
    public static function delete_matrix_for_user($user_id,$id){if(!self::user_owns_matrix($id,$user_id))return new WP_Error('sc_matrix_forbidden',__('That evidence matrix is not available to this account.','sustainable-catalyst-library'),array('status'=>403));return (bool)wp_delete_post(absint($id),true);}

    public static function add_claim_for_user($user_id,$matrix_id,$in){if(!self::user_owns_matrix($matrix_id,$user_id))return new WP_Error('sc_matrix_forbidden',__('That evidence matrix is not available to this account.','sustainable-catalyst-library'),array('status'=>403));$x=self::sanitize_claim($in,true);if(!$x['statement'])return new WP_Error('sc_matrix_claim_statement',__('Enter the claim statement.','sustainable-catalyst-library'));$claims=self::claims_for_matrix($matrix_id);if(count($claims)>=self::MAX_CLAIMS_PER_MATRIX)return new WP_Error('sc_matrix_claim_limit',__('The claim limit has been reached for this matrix.','sustainable-catalyst-library'));$x['created_at']=self::now();$x['updated_at']=$x['created_at'];$x['created_by']=absint($user_id);$claims[]=$x;self::write_array_meta($matrix_id,self::META_CLAIMS,$claims,self::MAX_CLAIMS_PER_MATRIX);do_action('sc_library_matrix_claim_created',$matrix_id,$x,$user_id);return $x;}
    public static function update_claim_for_user($user_id,$matrix_id,$claim_id,$in){if(!self::user_owns_matrix($matrix_id,$user_id))return new WP_Error('sc_matrix_forbidden',__('That evidence matrix is not available to this account.','sustainable-catalyst-library'),array('status'=>403));$next=array();$found=null;foreach(self::claims_for_matrix($matrix_id) as $c){if($c['id']===$claim_id){$merged=array_merge($c,(array)$in,array('id'=>$c['id'],'created_at'=>$c['created_at'],'created_by'=>$c['created_by'],'updated_at'=>self::now()));$c=self::sanitize_claim($merged,false);$found=$c;}$next[]=$c;}if(!$found)return new WP_Error('sc_matrix_claim_missing',__('That matrix claim was not found.','sustainable-catalyst-library'),array('status'=>404));if(!$found['statement'])return new WP_Error('sc_matrix_claim_statement',__('Enter the claim statement.','sustainable-catalyst-library'));self::write_array_meta($matrix_id,self::META_CLAIMS,$next,self::MAX_CLAIMS_PER_MATRIX);return $found;}
    public static function delete_claim_for_user($user_id,$matrix_id,$claim_id){if(!self::user_owns_matrix($matrix_id,$user_id))return new WP_Error('sc_matrix_forbidden',__('That evidence matrix is not available to this account.','sustainable-catalyst-library'),array('status'=>403));$claims=array_values(array_filter(self::claims_for_matrix($matrix_id),static fn($c)=>$c['id']!==$claim_id));$links=array_values(array_filter(self::links_for_matrix($matrix_id),static fn($l)=>$l['claim_id']!==$claim_id));self::write_array_meta($matrix_id,self::META_CLAIMS,$claims,self::MAX_CLAIMS_PER_MATRIX);self::write_array_meta($matrix_id,self::META_LINKS,$links,self::MAX_LINKS_PER_MATRIX);return true;}

    public static function add_link_for_user($user_id,$matrix_id,$in){if(!self::user_owns_matrix($matrix_id,$user_id))return new WP_Error('sc_matrix_forbidden',__('That evidence matrix is not available to this account.','sustainable-catalyst-library'),array('status'=>403));$link=self::sanitize_link($in,true);$claim_ids=array_column(self::claims_for_matrix($matrix_id),'id');if(!in_array($link['claim_id'],$claim_ids,true))return new WP_Error('sc_matrix_claim_missing',__('Choose a claim in this matrix.','sustainable-catalyst-library'));if($link['source_kind']!=='external'&&!$link['source_ref'])return new WP_Error('sc_matrix_source_required',__('Choose a source, note, annotation, or evidence record.','sustainable-catalyst-library'));if($link['source_kind']==='external'&&!$link['source_url']&&!$link['source_label'])return new WP_Error('sc_matrix_source_required',__('Enter an external source label or URL.','sustainable-catalyst-library'));$resolved=self::resolve_link_source($user_id,$link);if(empty($resolved['resolved']))return new WP_Error('sc_matrix_source_unresolved',__('That evidence reference could not be resolved for this account.','sustainable-catalyst-library'));$link=self::enrich_link($user_id,$link);$link['created_at']=self::now();$link['updated_at']=$link['created_at'];$link['created_by']=absint($user_id);$links=self::links_for_matrix($matrix_id);if(count($links)>=self::MAX_LINKS_PER_MATRIX)return new WP_Error('sc_matrix_link_limit',__('The evidence-link limit has been reached for this matrix.','sustainable-catalyst-library'));$links[]=$link;self::write_array_meta($matrix_id,self::META_LINKS,$links,self::MAX_LINKS_PER_MATRIX);do_action('sc_library_matrix_evidence_linked',$matrix_id,$link,$user_id);return $link;}
    public static function update_link_for_user($user_id,$matrix_id,$link_id,$in){if(!self::user_owns_matrix($matrix_id,$user_id))return new WP_Error('sc_matrix_forbidden',__('That evidence matrix is not available to this account.','sustainable-catalyst-library'),array('status'=>403));$next=array();$found=null;foreach(self::links_for_matrix($matrix_id) as $l){if($l['id']===$link_id){$merged=array_merge($l,(array)$in,array('id'=>$l['id'],'created_at'=>$l['created_at'],'created_by'=>$l['created_by'],'updated_at'=>self::now()));$l=self::sanitize_link($merged,false);$claim_ids=array_column(self::claims_for_matrix($matrix_id),'id');if(!in_array($l['claim_id'],$claim_ids,true))return new WP_Error('sc_matrix_claim_missing',__('Choose a claim in this matrix.','sustainable-catalyst-library'));$l=self::enrich_link($user_id,$l);$found=$l;}$next[]=$l;}if(!$found)return new WP_Error('sc_matrix_link_missing',__('That evidence link was not found.','sustainable-catalyst-library'),array('status'=>404));self::write_array_meta($matrix_id,self::META_LINKS,$next,self::MAX_LINKS_PER_MATRIX);return $found;}
    public static function delete_link_for_user($user_id,$matrix_id,$link_id){if(!self::user_owns_matrix($matrix_id,$user_id))return new WP_Error('sc_matrix_forbidden',__('That evidence matrix is not available to this account.','sustainable-catalyst-library'),array('status'=>403));$next=array_values(array_filter(self::links_for_matrix($matrix_id),static fn($l)=>$l['id']!==$link_id));self::write_array_meta($matrix_id,self::META_LINKS,$next,self::MAX_LINKS_PER_MATRIX);return true;}

    public static function diagnostics_for_claim($claim,$links){$claim_id=$claim['id'];$mine=array_values(array_filter($links,static fn($l)=>$l['claim_id']===$claim_id));$totals=array_fill_keys(array_keys(self::RELATIONS),0);$sources=array();$unresolved=0;$checked=0;foreach($mine as $l){$totals[$l['relation']]++;$k=(string)($l['source_key']??'');if($k)$sources[$k]=true;if(empty($l['resolution']['resolved']))$unresolved++;if(!empty($l['quote_checked'])&&!empty($l['locator_checked']))$checked++;}$gaps=array();if(!$mine)$gaps[]='no_evidence';if(!$totals['supports'])$gaps[]='no_supporting_evidence';if(!$totals['contradicts'])$gaps[]='no_counterevidence_recorded';if(count($sources)<=1&&count($mine)>1)$gaps[]='single_source_dependency';if($unresolved)$gaps[]='unresolved_references';if($mine&&$checked<count($mine))$gaps[]='unchecked_quote_or_locator';$pattern='no-evidence';if($mine){if($totals['supports']&&$totals['contradicts'])$pattern='mixed-record';elseif($totals['contradicts']&&!$totals['supports'])$pattern='contradiction-heavy';elseif($totals['supports']&&!$totals['contradicts'])$pattern='support-only';else $pattern='context-or-unresolved-only';}return array('schema'=>self::DIAGNOSTIC_SCHEMA,'claim_id'=>$claim_id,'evidence_count'=>count($mine),'relation_totals'=>$totals,'unique_source_count'=>count($sources),'fully_checked_link_count'=>$checked,'unresolved_reference_count'=>$unresolved,'pattern'=>$pattern,'gaps'=>$gaps,'interpretation'=>'descriptive-only','changes_claim_status'=>false,'changes_confidence'=>false);}
    public static function matrix_state($matrix_id,$user_id){if(!self::user_owns_matrix($matrix_id,$user_id))return new WP_Error('sc_matrix_forbidden',__('That evidence matrix is not available to this account.','sustainable-catalyst-library'),array('status'=>403));$p=get_post($matrix_id);$uuid=(string)get_post_meta($matrix_id,self::META_UUID,true);if(!$uuid){$uuid=self::new_uuid();update_post_meta($matrix_id,self::META_UUID,$uuid);}$claims=self::claims_for_matrix($matrix_id);$links=array_map(static fn($l)=>self::enrich_link($user_id,$l),self::links_for_matrix($matrix_id));$diag=array();foreach($claims as $c)$diag[$c['id']]=self::diagnostics_for_claim($c,$links);return array('schema'=>self::SCHEMA,'version'=>self::VERSION,'matrix_id'=>absint($matrix_id),'uuid'=>$uuid,'urn'=>'urn:sc:evidence-matrix:'.$uuid,'title'=>$p?$p->post_title:'','owner_user_id'=>absint($user_id),'visibility'=>'private','status'=>self::enum_value(get_post_meta($matrix_id,self::META_STATUS,true),self::MATRIX_STATUSES,'active'),'project_context'=>self::context($matrix_id,$user_id),'claims'=>$claims,'evidence_links'=>$links,'claim_count'=>count($claims),'evidence_link_count'=>count($links),'diagnostics'=>$diag,'contract'=>self::contract(),'updated_at'=>(string)get_post_meta($matrix_id,self::META_UPDATED_AT,true));}
    public static function state_for_user($user_id){$items=array();foreach(self::matrices_for_user($user_id) as $id){$x=self::matrix_state($id,$user_id);if(!is_wp_error($x))$items[]=$x;}return array('schema'=>'sc-library-evidence-matrices-state/1.0','version'=>self::VERSION,'visibility'=>'private','user_id'=>absint($user_id),'matrices'=>$items,'matrix_count'=>count($items),'contract'=>self::contract());}
    public static function matrix_manifest($matrix_id,$user_id){$state=self::matrix_state($matrix_id,$user_id);if(is_wp_error($state))return $state;$manifest=array('schema'=>'sc-library-evidence-matrix-manifest/1.0','version'=>self::VERSION,'matrix'=>$state,'generated_at'=>self::now(),'content_contract'=>array('relationships_explicitly_created_by_user'=>true,'diagnostics_descriptive_only'=>true,'underlying_source_records_referenced_not_copied'=>true,'private_binaries_excluded'=>true));$manifest['checksum_sha256']=hash('sha256',wp_json_encode($manifest));return $manifest;}

    public static function source_catalog_for_user($user_id){$out=array();if(class_exists('SC_Library_Reading_Notebook_Annotations'))foreach(SC_Library_Reading_Notebook_Annotations::notebooks_for_user($user_id) as $nid){$state=SC_Library_Reading_Notebook_Annotations::notebook_state($nid,$user_id);if(is_wp_error($state))continue;foreach((array)$state['notes'] as $r){if(empty($r['excerpt'])&&empty($r['body']))continue;$res=(array)($r['source_resolution']??array());$out[]=array('kind'=>'reading_note','ref'=>$nid.':'.$r['id'],'label'=>($r['title']?:'Reading note').' — '.($res['label']??get_the_title($nid)),'source_label'=>$res['label']??($r['source_label']??''),'source_url'=>$res['url']??($r['source_url']??''));}foreach((array)$state['annotations'] as $r){if(empty($r['excerpt'])&&empty($r['body']))continue;$res=(array)($r['source_resolution']??array());$out[]=array('kind'=>'source_annotation','ref'=>$nid.':'.$r['id'],'label'=>'Annotation — '.($res['label']??get_the_title($nid)),'source_label'=>$res['label']??($r['source_label']??''),'source_url'=>$res['url']??($r['source_url']??''));}}
        if(class_exists('SC_Library_Evidence_Claim_Linking')){$ids=get_posts(array('post_type'=>SC_Library_Evidence_Claim_Linking::NOTE_POST_TYPE,'post_status'=>array('private','draft','publish','pending'),'author'=>absint($user_id),'posts_per_page'=>100,'orderby'=>'modified','order'=>'DESC','fields'=>'ids'));foreach($ids as $id){$d=SC_Library_Evidence_Claim_Linking::get_evidence_data($id,true);if($d)$out[]=array('kind'=>'canonical_evidence','ref'=>(string)$id,'label'=>'Evidence Note — '.$d['title'],'source_label'=>$d['source_title']??'','source_url'=>$d['source_url']??'');}}
        if(class_exists('SC_Library_Unified_Research_Projects_Source_Bundles'))foreach(SC_Library_Unified_Research_Projects_Source_Bundles::reference_catalog_for_user($user_id) as $r){$out[]=array('kind'=>'project_reference','ref'=>($r['family']??'external').':'.($r['ref_id']??''),'label'=>'Project reference — '.($r['label']??''),'source_label'=>$r['label']??'','source_url'=>$r['url']??'');}
        return $out;
    }
    private static function project_catalog($user_id){$out=array();if(!class_exists('SC_Library_Unified_Research_Projects_Source_Bundles'))return $out;foreach(SC_Library_Unified_Research_Projects_Source_Bundles::projects_for_user($user_id) as $pid){$p=array('project_id'=>$pid,'title'=>get_the_title($pid),'bundles'=>array());foreach(SC_Library_Unified_Research_Projects_Source_Bundles::bundles_for_project($pid) as $b)$p['bundles'][]=array('bundle_id'=>$b['bundle_id'],'title'=>$b['title']);$out[]=$p;}return $out;}

    private static function render_context_select($projects,$pid=0,$bid=''){$html='<label><span>'.esc_html__('Project / source bundle','sustainable-catalyst-library').'</span><select name="context"><option value="0|">'.esc_html__('No project attachment','sustainable-catalyst-library').'</option>';foreach($projects as $p){$sel=$pid==$p['project_id']&&$bid===''?' selected':'';$html.='<option value="'.esc_attr($p['project_id'].'|').'"'.$sel.'>'.esc_html($p['title']).'</option>';foreach($p['bundles'] as $b){$sel=$pid==$p['project_id']&&$bid===$b['bundle_id']?' selected':'';$html.='<option value="'.esc_attr($p['project_id'].'|'.$b['bundle_id']).'"'.$sel.'>↳ '.esc_html($p['title'].' / '.$b['title']).'</option>';}}return $html.'</select></label>';}
    private static function render_source_select($catalog){$html='<label><span>'.esc_html__('Evidence source','sustainable-catalyst-library').'</span><select name="source_choice"><option value="external|">'.esc_html__('External source','sustainable-catalyst-library').'</option>';foreach($catalog as $r)$html.='<option value="'.esc_attr($r['kind'].'|'.$r['ref']).'">'.esc_html($r['label']).'</option>';return $html.'</select></label>';}
    private static function status_label($key,$map){return $map[$key]??$key;}
    private static function render_matrix($state,$projects,$catalog){$mid=$state['matrix_id'];$ctx=$state['project_context'];$claims=$state['claims'];$links=$state['evidence_links'];ob_start();?><article class="sc-evidence-matrix__matrix" data-matrix-id="<?php echo esc_attr($mid); ?>"><header><div><small><?php echo esc_html($ctx['project_title']?:__('Private evidence matrix','sustainable-catalyst-library')); ?></small><h4><?php echo esc_html($state['title']); ?></h4><p><?php echo esc_html(sprintf(__('%1$d claims · %2$d evidence relationships','sustainable-catalyst-library'),$state['claim_count'],$state['evidence_link_count'])); ?></p></div><span><?php echo esc_html(self::status_label($state['status'],self::MATRIX_STATUSES)); ?></span></header>
        <details><summary><?php esc_html_e('Matrix settings','sustainable-catalyst-library'); ?></summary><form data-sc-matrix-update><input type="hidden" name="matrix_id" value="<?php echo esc_attr($mid); ?>"><label><span><?php esc_html_e('Title','sustainable-catalyst-library'); ?></span><input name="title" value="<?php echo esc_attr($state['title']); ?>" required></label><?php echo self::render_context_select($projects,$ctx['project_id'],$ctx['bundle_id']); ?><label><span><?php esc_html_e('Status','sustainable-catalyst-library'); ?></span><select name="status"><?php foreach(self::MATRIX_STATUSES as $k=>$v):?><option value="<?php echo esc_attr($k); ?>" <?php selected($state['status'],$k); ?>><?php echo esc_html($v); ?></option><?php endforeach;?></select></label><div class="sc-evidence-matrix__actions"><button type="submit"><?php esc_html_e('Save matrix','sustainable-catalyst-library'); ?></button><button type="button" class="is-danger" data-sc-matrix-delete="<?php echo esc_attr($mid); ?>"><?php esc_html_e('Delete matrix','sustainable-catalyst-library'); ?></button></div></form></details>
        <div class="sc-evidence-matrix__add-grid"><details><summary><?php esc_html_e('Add claim','sustainable-catalyst-library'); ?></summary><form data-sc-matrix-add-claim><input type="hidden" name="matrix_id" value="<?php echo esc_attr($mid); ?>"><label><span><?php esc_html_e('Short label','sustainable-catalyst-library'); ?></span><input name="title"></label><label><span><?php esc_html_e('Claim statement','sustainable-catalyst-library'); ?></span><textarea name="statement" rows="3" required></textarea></label><div class="sc-evidence-matrix__grid"><label><span><?php esc_html_e('Status','sustainable-catalyst-library'); ?></span><select name="status"><?php foreach(self::CLAIM_STATUSES as $k=>$v):?><option value="<?php echo esc_attr($k); ?>"><?php echo esc_html($v); ?></option><?php endforeach;?></select></label><label><span><?php esc_html_e('Confidence (user declared)','sustainable-catalyst-library'); ?></span><select name="confidence"><?php foreach(self::CONFIDENCE as $k=>$v):?><option value="<?php echo esc_attr($k); ?>"><?php echo esc_html($v); ?></option><?php endforeach;?></select></label></div><label><span><?php esc_html_e('Scope / conditions','sustainable-catalyst-library'); ?></span><textarea name="scope" rows="2"></textarea></label><label><span><?php esc_html_e('Assumptions','sustainable-catalyst-library'); ?></span><textarea name="assumptions" rows="2"></textarea></label><label><span><?php esc_html_e('Limitations','sustainable-catalyst-library'); ?></span><textarea name="limitations" rows="2"></textarea></label><label><span><?php esc_html_e('Plausible counterclaim','sustainable-catalyst-library'); ?></span><textarea name="counterclaim" rows="2"></textarea></label><label><span><?php esc_html_e('Tags','sustainable-catalyst-library'); ?></span><input name="tags"></label><button type="submit"><?php esc_html_e('Add claim','sustainable-catalyst-library'); ?></button></form></details>
        <?php if($claims):?><details><summary><?php esc_html_e('Link evidence to a claim','sustainable-catalyst-library'); ?></summary><form data-sc-matrix-add-link><input type="hidden" name="matrix_id" value="<?php echo esc_attr($mid); ?>"><label><span><?php esc_html_e('Claim','sustainable-catalyst-library'); ?></span><select name="claim_id"><?php foreach($claims as $c):?><option value="<?php echo esc_attr($c['id']); ?>"><?php echo esc_html($c['title']?:wp_trim_words($c['statement'],12)); ?></option><?php endforeach;?></select></label><label><span><?php esc_html_e('Relationship','sustainable-catalyst-library'); ?></span><select name="relation"><?php foreach(self::RELATIONS as $k=>$v):?><option value="<?php echo esc_attr($k); ?>"><?php echo esc_html($v); ?></option><?php endforeach;?></select></label><?php echo self::render_source_select($catalog); ?><div class="sc-evidence-matrix__grid"><label><span><?php esc_html_e('External/source label','sustainable-catalyst-library'); ?></span><input name="source_label"></label><label><span><?php esc_html_e('External/source URL','sustainable-catalyst-library'); ?></span><input type="url" name="source_url"></label></div><div class="sc-evidence-matrix__grid"><label><span><?php esc_html_e('Locator type','sustainable-catalyst-library'); ?></span><select name="locator_type"><?php foreach(self::LOCATOR_TYPES as $k=>$v):?><option value="<?php echo esc_attr($k); ?>"><?php echo esc_html($v); ?></option><?php endforeach;?></select></label><label><span><?php esc_html_e('Locator','sustainable-catalyst-library'); ?></span><input name="locator_value"></label></div><label><span><?php esc_html_e('Selected passage / data point','sustainable-catalyst-library'); ?></span><textarea name="excerpt" rows="3" maxlength="<?php echo esc_attr(self::MAX_EXCERPT_CHARS); ?>"></textarea></label><label><span><?php esc_html_e('Why this evidence bears on the claim','sustainable-catalyst-library'); ?></span><textarea name="rationale" rows="2"></textarea></label><div class="sc-evidence-matrix__checks"><label><input type="checkbox" name="quote_checked" value="1"><span><?php esc_html_e('Wording / transcription checked','sustainable-catalyst-library'); ?></span></label><label><input type="checkbox" name="locator_checked" value="1"><span><?php esc_html_e('Locator checked','sustainable-catalyst-library'); ?></span></label></div><button type="submit"><?php esc_html_e('Link evidence','sustainable-catalyst-library'); ?></button></form></details><?php endif;?></div>
        <div class="sc-evidence-matrix__claims"><?php if(!$claims):?><p class="sc-evidence-matrix__empty"><?php esc_html_e('No claims yet. Add a working claim, then attach evidence explicitly.','sustainable-catalyst-library'); ?></p><?php else:foreach($claims as $c):$d=$state['diagnostics'][$c['id']];$mine=array_values(array_filter($links,static fn($l)=>$l['claim_id']===$c['id']));?><section class="sc-evidence-matrix__claim"><header><div><small><?php echo esc_html(self::status_label($c['status'],self::CLAIM_STATUSES).' · '.self::status_label($c['confidence'],self::CONFIDENCE)); ?></small><h5><?php echo esc_html($c['title']?:__('Working claim','sustainable-catalyst-library')); ?></h5></div><button type="button" data-sc-matrix-delete-claim="<?php echo esc_attr($c['id']); ?>" data-matrix-id="<?php echo esc_attr($mid); ?>"><?php esc_html_e('Remove','sustainable-catalyst-library'); ?></button></header><p class="sc-evidence-matrix__statement"><?php echo esc_html($c['statement']); ?></p>
            <div class="sc-evidence-matrix__diagnostics"><strong><?php esc_html_e('Descriptive diagnostics','sustainable-catalyst-library'); ?></strong><span><?php echo esc_html(sprintf(__('%1$d links · %2$d unique source keys · pattern: %3$s','sustainable-catalyst-library'),$d['evidence_count'],$d['unique_source_count'],$d['pattern'])); ?></span><?php if($d['gaps']):?><ul><?php foreach($d['gaps'] as $gap):?><li><?php echo esc_html(str_replace('_',' ',$gap)); ?></li><?php endforeach;?></ul><?php endif;?><em><?php esc_html_e('These counts do not change the claim status or confidence.','sustainable-catalyst-library'); ?></em></div>
            <?php if($mine):?><div class="sc-evidence-matrix__links"><?php foreach($mine as $l):?><article><div><small><?php echo esc_html(self::status_label($l['relation'],self::RELATIONS)); ?></small><strong><?php echo esc_html($l['source_label']?:__('Referenced evidence','sustainable-catalyst-library')); ?></strong><?php if($l['locator_value']):?><span><?php echo esc_html(self::status_label($l['locator_type'],self::LOCATOR_TYPES).': '.$l['locator_value']); ?></span><?php endif;?><?php if($l['excerpt']):?><blockquote><?php echo esc_html($l['excerpt']); ?></blockquote><?php endif;?><?php if($l['rationale']):?><p><?php echo esc_html($l['rationale']); ?></p><?php endif;?><span><?php echo esc_html(($l['quote_checked']?'wording checked':'wording unchecked').' · '.($l['locator_checked']?'locator checked':'locator unchecked')); ?></span></div><button type="button" data-sc-matrix-delete-link="<?php echo esc_attr($l['id']); ?>" data-matrix-id="<?php echo esc_attr($mid); ?>"><?php esc_html_e('Remove','sustainable-catalyst-library'); ?></button></article><?php endforeach;?></div><?php endif;?></section><?php endforeach;endif;?></div>
        <footer><strong><?php esc_html_e('v4.3.32 boundary','sustainable-catalyst-library'); ?></strong><span><?php esc_html_e('Evidence relationships are explicit. Diagnostics summarize recorded relationships and gaps; they do not infer truth, generate claims, alter confidence, publish records, or write into Workspace automatically.','sustainable-catalyst-library'); ?></span></footer></article><?php return ob_get_clean();}

    public function shortcode($atts){$atts=shortcode_atts(array('title'=>'Evidence Matrix & Claim Intelligence'),$atts,'sc_evidence_matrix_workspace');wp_enqueue_style('sc-library-evidence-matrix-v4332');wp_enqueue_script('sc-library-evidence-matrix-v4332');$signed=is_user_logged_in();$uid=$signed?get_current_user_id():0;$projects=$signed?self::project_catalog($uid):array();$catalog=$signed?self::source_catalog_for_user($uid):array();wp_localize_script('sc-library-evidence-matrix-v4332','SCLibraryEvidenceMatrix',array('ajaxUrl'=>admin_url('admin-ajax.php'),'nonce'=>wp_create_nonce(self::NONCE_ACTION),'signedIn'=>$signed,'schema'=>self::SCHEMA));ob_start();?><section class="sc-evidence-matrix" data-sc-evidence-matrix="v4.3.32"><header class="sc-evidence-matrix__hero"><div><p><?php esc_html_e('Private evidence reasoning workspace','sustainable-catalyst-library'); ?></p><h3><?php echo esc_html($atts['title']); ?></h3><span><?php esc_html_e('Compare claims against explicitly linked evidence, counterevidence, qualifiers, and context without collapsing source material, notes, and interpretation into one record.','sustainable-catalyst-library'); ?></span></div><aside><strong><?php esc_html_e('No automatic conclusions','sustainable-catalyst-library'); ?></strong><span><?php esc_html_e('Claim Intelligence is deterministic and descriptive: relation counts, source diversity, unresolved references, and review gaps. You decide what the evidence means.','sustainable-catalyst-library'); ?></span></aside></header><?php if(!$signed):?><div class="sc-evidence-matrix__signin"><strong><?php esc_html_e('Sign in to build private evidence matrices.','sustainable-catalyst-library'); ?></strong><a href="<?php echo esc_url(wp_login_url(SC_Library_Canonical_Route_Identity::canonical_url())); ?>"><?php esc_html_e('Sign in →','sustainable-catalyst-library'); ?></a></div><?php else:$states=self::state_for_user($uid);?><div class="sc-evidence-matrix__create"><form data-sc-matrix-create><label><span><?php esc_html_e('Matrix title','sustainable-catalyst-library'); ?></span><input name="title" required placeholder="<?php esc_attr_e('e.g. Grid resilience evidence review','sustainable-catalyst-library'); ?>"></label><?php echo self::render_context_select($projects); ?><button type="submit"><?php esc_html_e('Create evidence matrix','sustainable-catalyst-library'); ?></button><span data-sc-matrix-status aria-live="polite"></span></form></div><div class="sc-evidence-matrix__list"><?php if(!$states['matrices']):?><p class="sc-evidence-matrix__empty"><?php esc_html_e('No evidence matrices yet. Create one above, preferably attached to a Research Project.','sustainable-catalyst-library'); ?></p><?php else:foreach($states['matrices'] as $state)echo self::render_matrix($state,$projects,$catalog);endif;?></div><?php endif;?></section><?php return ob_get_clean();}

    private static function ajax_guard(){check_ajax_referer(self::NONCE_ACTION,'nonce');if(!is_user_logged_in())wp_send_json_error(array('message'=>__('Sign in required.','sustainable-catalyst-library')),401);return get_current_user_id();}
    private static function context_input($raw){$parts=explode('|',(string)$raw,2);return array(absint($parts[0]??0),self::clean_text($parts[1]??'',80));}
    private static function source_input($raw){$parts=explode('|',(string)$raw,2);return array(self::enum_value($parts[0]??'',self::SOURCE_KINDS,'external'),self::clean_text($parts[1]??'',360));}
    private static function ajax_result($r){if(is_wp_error($r)){$data=$r->get_error_data();$status=is_array($data)&&isset($data['status'])?absint($data['status']):400;wp_send_json_error(array('message'=>$r->get_error_message()),$status);}wp_send_json_success($r);}
    public function ajax_create_matrix(){$uid=self::ajax_guard();[$pid,$bid]=self::context_input(wp_unslash($_POST['context']??''));self::ajax_result(self::create_matrix_for_user($uid,array('title'=>wp_unslash($_POST['title']??''),'project_id'=>$pid,'bundle_id'=>$bid)));}
    public function ajax_update_matrix(){$uid=self::ajax_guard();[$pid,$bid]=self::context_input(wp_unslash($_POST['context']??''));self::ajax_result(self::update_matrix_for_user($uid,absint($_POST['matrix_id']??0),array('title'=>wp_unslash($_POST['title']??''),'status'=>wp_unslash($_POST['status']??''),'project_id'=>$pid,'bundle_id'=>$bid)));}
    public function ajax_delete_matrix(){$uid=self::ajax_guard();self::ajax_result(self::delete_matrix_for_user($uid,absint($_POST['matrix_id']??0)));}
    public function ajax_add_claim(){$uid=self::ajax_guard();$in=array();foreach(array('title','statement','status','confidence','scope','assumptions','limitations','counterclaim','tags','position') as $k)$in[$k]=wp_unslash($_POST[$k]??'');self::ajax_result(self::add_claim_for_user($uid,absint($_POST['matrix_id']??0),$in));}
    public function ajax_update_claim(){$uid=self::ajax_guard();$in=array();foreach(array('title','statement','status','confidence','scope','assumptions','limitations','counterclaim','tags','position') as $k)if(isset($_POST[$k]))$in[$k]=wp_unslash($_POST[$k]);self::ajax_result(self::update_claim_for_user($uid,absint($_POST['matrix_id']??0),self::clean_text(wp_unslash($_POST['claim_id']??''),80),$in));}
    public function ajax_delete_claim(){$uid=self::ajax_guard();self::ajax_result(self::delete_claim_for_user($uid,absint($_POST['matrix_id']??0),self::clean_text(wp_unslash($_POST['claim_id']??''),80)));}
    public function ajax_add_link(){$uid=self::ajax_guard();[$kind,$ref]=self::source_input(wp_unslash($_POST['source_choice']??''));$in=array('claim_id'=>wp_unslash($_POST['claim_id']??''),'relation'=>wp_unslash($_POST['relation']??''),'source_kind'=>$kind,'source_ref'=>$ref,'source_label'=>wp_unslash($_POST['source_label']??''),'source_url'=>wp_unslash($_POST['source_url']??''),'locator_type'=>wp_unslash($_POST['locator_type']??''),'locator_value'=>wp_unslash($_POST['locator_value']??''),'excerpt'=>wp_unslash($_POST['excerpt']??''),'rationale'=>wp_unslash($_POST['rationale']??''),'quote_checked'=>!empty($_POST['quote_checked']),'locator_checked'=>!empty($_POST['locator_checked']));self::ajax_result(self::add_link_for_user($uid,absint($_POST['matrix_id']??0),$in));}
    public function ajax_update_link(){$uid=self::ajax_guard();$in=array();foreach(array('claim_id','relation','source_kind','source_ref','source_label','source_url','locator_type','locator_value','excerpt','rationale','quote_checked','locator_checked') as $k)if(isset($_POST[$k]))$in[$k]=wp_unslash($_POST[$k]);self::ajax_result(self::update_link_for_user($uid,absint($_POST['matrix_id']??0),self::clean_text(wp_unslash($_POST['link_id']??''),80),$in));}
    public function ajax_delete_link(){$uid=self::ajax_guard();self::ajax_result(self::delete_link_for_user($uid,absint($_POST['matrix_id']??0),self::clean_text(wp_unslash($_POST['link_id']??''),80)));}

    public function register_rest_routes(){register_rest_route(self::REST_NAMESPACE,self::REST_ROUTE,array(array('methods'=>WP_REST_Server::READABLE,'permission_callback'=>array($this,'rest_signed_in'),'callback'=>array($this,'rest_list')),array('methods'=>WP_REST_Server::CREATABLE,'permission_callback'=>array($this,'rest_signed_in'),'callback'=>array($this,'rest_create'))));register_rest_route(self::REST_NAMESPACE,self::REST_ROUTE.'/(?P<id>\\d+)',array(array('methods'=>WP_REST_Server::READABLE,'permission_callback'=>array($this,'rest_owns_matrix'),'callback'=>array($this,'rest_get')),array('methods'=>WP_REST_Server::EDITABLE,'permission_callback'=>array($this,'rest_owns_matrix'),'callback'=>array($this,'rest_update')),array('methods'=>WP_REST_Server::DELETABLE,'permission_callback'=>array($this,'rest_owns_matrix'),'callback'=>array($this,'rest_delete'))));register_rest_route(self::REST_NAMESPACE,self::REST_ROUTE.'/(?P<id>\\d+)/manifest',array('methods'=>WP_REST_Server::READABLE,'permission_callback'=>array($this,'rest_owns_matrix'),'callback'=>array($this,'rest_manifest')));register_rest_route(self::REST_NAMESPACE,self::REST_ROUTE.'/(?P<id>\\d+)/claims',array('methods'=>WP_REST_Server::CREATABLE,'permission_callback'=>array($this,'rest_owns_matrix'),'callback'=>array($this,'rest_add_claim')));register_rest_route(self::REST_NAMESPACE,self::REST_ROUTE.'/(?P<id>\\d+)/claims/(?P<claim_id>[A-Za-z0-9\\-]+)',array(array('methods'=>WP_REST_Server::EDITABLE,'permission_callback'=>array($this,'rest_owns_matrix'),'callback'=>array($this,'rest_update_claim')),array('methods'=>WP_REST_Server::DELETABLE,'permission_callback'=>array($this,'rest_owns_matrix'),'callback'=>array($this,'rest_delete_claim'))));register_rest_route(self::REST_NAMESPACE,self::REST_ROUTE.'/(?P<id>\\d+)/links',array('methods'=>WP_REST_Server::CREATABLE,'permission_callback'=>array($this,'rest_owns_matrix'),'callback'=>array($this,'rest_add_link')));register_rest_route(self::REST_NAMESPACE,self::REST_ROUTE.'/(?P<id>\\d+)/links/(?P<link_id>[A-Za-z0-9\\-]+)',array(array('methods'=>WP_REST_Server::EDITABLE,'permission_callback'=>array($this,'rest_owns_matrix'),'callback'=>array($this,'rest_update_link')),array('methods'=>WP_REST_Server::DELETABLE,'permission_callback'=>array($this,'rest_owns_matrix'),'callback'=>array($this,'rest_delete_link'))));}
    public function rest_signed_in(){return is_user_logged_in();}
    public function rest_owns_matrix($r){return is_user_logged_in()&&self::user_owns_matrix(absint($r['id']),get_current_user_id());}
    private static function json($r){$p=$r->get_json_params();return is_array($p)?$p:array();}
    public function rest_list(){return rest_ensure_response(self::state_for_user(get_current_user_id()));}
    public function rest_create($r){return rest_ensure_response(self::create_matrix_for_user(get_current_user_id(),self::json($r)));}
    public function rest_get($r){return rest_ensure_response(self::matrix_state(absint($r['id']),get_current_user_id()));}
    public function rest_update($r){return rest_ensure_response(self::update_matrix_for_user(get_current_user_id(),absint($r['id']),self::json($r)));}
    public function rest_delete($r){return rest_ensure_response(array('deleted'=>self::delete_matrix_for_user(get_current_user_id(),absint($r['id']))));}
    public function rest_manifest($r){return rest_ensure_response(self::matrix_manifest(absint($r['id']),get_current_user_id()));}
    public function rest_add_claim($r){return rest_ensure_response(self::add_claim_for_user(get_current_user_id(),absint($r['id']),self::json($r)));}
    public function rest_update_claim($r){return rest_ensure_response(self::update_claim_for_user(get_current_user_id(),absint($r['id']),self::clean_text($r['claim_id'],80),self::json($r)));}
    public function rest_delete_claim($r){return rest_ensure_response(array('deleted'=>self::delete_claim_for_user(get_current_user_id(),absint($r['id']),self::clean_text($r['claim_id'],80))));}
    public function rest_add_link($r){return rest_ensure_response(self::add_link_for_user(get_current_user_id(),absint($r['id']),self::json($r)));}
    public function rest_update_link($r){return rest_ensure_response(self::update_link_for_user(get_current_user_id(),absint($r['id']),self::clean_text($r['link_id'],80),self::json($r)));}
    public function rest_delete_link($r){return rest_ensure_response(array('deleted'=>self::delete_link_for_user(get_current_user_id(),absint($r['id']),self::clean_text($r['link_id'],80))));}

    public function filter_matrix_state($state,$matrix_id,$user_id){$x=self::matrix_state($matrix_id,$user_id);return is_wp_error($x)?$state:$x;}
    public function filter_matrix_manifest($manifest,$matrix_id,$user_id){$x=self::matrix_manifest($matrix_id,$user_id);return is_wp_error($x)?$manifest:$x;}
    public function action_create_claim($matrix_id,$input,$user_id){self::add_claim_for_user($user_id,$matrix_id,$input);}
    public function action_link_evidence($matrix_id,$input,$user_id){self::add_link_for_user($user_id,$matrix_id,$input);}
}
