export type Json = null | boolean | number | string | Json[] | {[key:string]:Json};
export interface ClientOptions { apiKey?: string | null; maxRetries?: number; fetchImpl?: typeof fetch; }
export class LibraryError extends Error { status:number|null; code:string|null; details:unknown; }
export function signRequest(method:string,path:string,timestamp:string,body:string,key:string):Promise<string>;
export class ProductAdapter { productKey:string; contract():Promise<any>; validateExchange(payload:Record<string,unknown>):Promise<any>; }
export class LibraryClient {
  constructor(baseUrl:string, options?:ClientOptions);
  health():Promise<any>; readiness():Promise<any>; service():Promise<any>; capabilities():Promise<any>; routes():Promise<any>; clientFramework():Promise<any>; catalog():Promise<any>; catalogReadiness():Promise<any>; researchObject(id:string,options?:{includeBody?:boolean}):Promise<any>; validateCatalogRecord(payload:Record<string,unknown>):Promise<any>; upsertCatalogRecord(payload:Record<string,unknown>):Promise<any>; deleteCatalogRecord(id:string):Promise<any>;
  provenance():Promise<any>; provenanceReadiness():Promise<any>; recordProvenance(id:string,options?:{versionLimit?:number}):Promise<any>; citations(id:string,options?:{direction?:string,limit?:number}):Promise<any>; evidenceGraph(id:string,options?:{depth?:number,limit?:number,includeCore?:boolean}):Promise<any>; createCitation(payload:Record<string,unknown>):Promise<any>; importCitations(id:string):Promise<any>; citationCoreHandoff(payload:Record<string,unknown>):Promise<any>;
  retrieval():Promise<any>; retrievalReadiness():Promise<any>; retrievalFacets():Promise<any>; retrievalSearch(q?:string,options?:Record<string,unknown>):Promise<any>; retrievalPlan(payload:Record<string,unknown>):Promise<any>; retrievalSearchAdvanced(payload:Record<string,unknown>):Promise<any>;
  researchState():Promise<any>; researchStateReadiness():Promise<any>; researchStateForOwner(id:string):Promise<any>; createResearchProject(payload:Record<string,unknown>):Promise<any>; addProjectReference(projectId:string,payload:Record<string,unknown>):Promise<any>; createSourceBundle(projectId:string,payload:Record<string,unknown>):Promise<any>; saveSearch(payload:Record<string,unknown>):Promise<any>; saveWatchlist(payload:Record<string,unknown>):Promise<any>; enqueueResearch(payload:Record<string,unknown>):Promise<any>; createCollection(payload:Record<string,unknown>):Promise<any>; addCollectionItem(collectionId:string,payload:Record<string,unknown>):Promise<any>;
  ingestion():Promise<any>; ingestionReadiness():Promise<any>; normalizeIngestion(payload:Record<string,unknown>):Promise<any>; ingestSourceRecords(payload:Record<string,unknown>):Promise<any>; sourceIngestionState(sourceKey:string):Promise<any>;
  search(q?:string,filters?:Record<string,unknown>):Promise<any>; record(id:string,options?:{includeBody?:boolean}):Promise<any>; stats():Promise<any>; integrations():Promise<any>;
  submitResearchJob(payload:Record<string,unknown>):Promise<any>; product(key:string):ProductAdapter; researchLibrarian():ProductAdapter; workspace():ProductAdapter; researchLab():ProductAdapter; workbench():ProductAdapter; decisionStudio():ProductAdapter; siteIntelligence():ProductAdapter;
}
