export type Json = null | boolean | number | string | Json[] | {[key:string]:Json};
export interface ClientOptions { apiKey?: string | null; maxRetries?: number; fetchImpl?: typeof fetch; }
export class LibraryError extends Error { status:number|null; code:string|null; details:unknown; }
export function signRequest(method:string,path:string,timestamp:string,body:string,key:string):Promise<string>;
export class ProductAdapter { productKey:string; contract():Promise<any>; validateExchange(payload:Record<string,unknown>):Promise<any>; }
export class LibraryClient {
  constructor(baseUrl:string, options?:ClientOptions);
  health():Promise<any>; readiness():Promise<any>; service():Promise<any>; capabilities():Promise<any>; routes():Promise<any>; clientFramework():Promise<any>; catalog():Promise<any>; catalogReadiness():Promise<any>; researchObject(id:string,options?:{includeBody?:boolean}):Promise<any>; validateCatalogRecord(payload:Record<string,unknown>):Promise<any>; upsertCatalogRecord(payload:Record<string,unknown>):Promise<any>; deleteCatalogRecord(id:string):Promise<any>;
  savedWorkspaces():Promise<any>; savedWorkspacesReadiness():Promise<any>;
  navigation():Promise<any>; navigationReadiness():Promise<any>; navigationBootstrap():Promise<any>; resolveNavigation(path:string):Promise<any>;
  researchInterface():Promise<any>; researchInterfaceReadiness():Promise<any>; researchInterfaceBootstrap():Promise<any>; researchInterfaceSearch(q?:string,options?:Record<string,unknown>):Promise<any>; researchInterfaceRecord(id:string,options?:{includeBody?:boolean,versionLimit?:number,evidenceDepth?:number,evidenceLimit?:number}):Promise<any>; researchInterfaceOwnerState(id:string):Promise<any>;
  libraryProduct():Promise<any>; libraryProductReadiness():Promise<any>; libraryProductRelease():Promise<any>;
  independentApplication():Promise<any>; independentApplicationReadiness():Promise<any>; independentApplicationCertification():Promise<any>; certifyIndependentApplication(payload?:Record<string,unknown>):Promise<any>;
  wordpressAdapter():Promise<any>; wordpressAdapterReadiness():Promise<any>; wordpressAdapterConsolidation():Promise<any>; certifyWordpressAdapterConsolidation(payload:Record<string,unknown>):Promise<any>;
  workflows():Promise<any>; workflowsReadiness():Promise<any>; validateWorkflowControl(payload:Record<string,unknown>):Promise<any>; workflowJobs(filters?:Record<string,unknown>):Promise<any>; workflowJob(id:string):Promise<any>; submitWorkflowJob(payload:Record<string,unknown>):Promise<any>; cancelWorkflowJob(id:string,reason?:string):Promise<any>; workflowWorkers():Promise<any>; workflowDeadLetters(options?:{state?:string,limit?:number}):Promise<any>; recoverWorkflowLeases(limit?:number):Promise<any>; validateWorkflowPipeline(payload:Record<string,unknown>):Promise<any>; createWorkflowPipeline(payload:Record<string,unknown>):Promise<any>; workflowPipeline(id:string):Promise<any>; resumeWorkflowPipeline(id:string):Promise<any>;
  federation(filters?:Record<string,unknown>):Promise<any>; federationReadiness():Promise<any>; federationSource(id:string):Promise<any>; federationConnector(id:string):Promise<any>; federationConnectorStatus(id:string):Promise<any>; federationCollections():Promise<any>; federationCertification():Promise<any>; globalFederation():Promise<any>; globalFederationReadiness():Promise<any>; globalFederationLenses():Promise<any>; globalFederationSource(id:string):Promise<any>; planGlobalFederation(payload:Record<string,unknown>):Promise<any>; globalFederatedDiscovery(payload:Record<string,unknown>):Promise<any>; validateFederationConnector(payload:Record<string,unknown>):Promise<any>; planFederationConnector(payload:Record<string,unknown>):Promise<any>; validateFederationCertification(payload:Record<string,unknown>):Promise<any>; createFederationCertification(payload?:Record<string,unknown>):Promise<any>;
  reproducibility():Promise<any>; reproducibilityReadiness():Promise<any>; runtimeReproducibilityStatus():Promise<any>; researchPackage(id:string,options?:{includeManifest?:boolean}):Promise<any>; validateResearchPackage(payload:Record<string,unknown>):Promise<any>; createResearchPackage(payload:Record<string,unknown>):Promise<any>; verifyResearchPackage(id:string,payload?:Record<string,unknown>):Promise<any>;
  language():Promise<any>; languageReadiness():Promise<any>; languageCapture(id:string,options?:{includeText?:boolean}):Promise<any>; languageDerivation(id:string,options?:{includeText?:boolean}):Promise<any>; linguisticCorpus(id:string,options?:{includeTokens?:boolean}):Promise<any>; linguisticKwic(id:string,q:string,options?:Record<string,unknown>):Promise<any>; languageResolutionCase(id:string):Promise<any>; languageAlignment(id:string):Promise<any>; scientificDocumentIntelligence(id:string):Promise<any>; validateLanguageCapture(payload:Record<string,unknown>):Promise<any>; createLanguageCapture(payload:Record<string,unknown>):Promise<any>; validateLanguageDerivation(payload:Record<string,unknown>):Promise<any>; createLanguageDerivation(payload:Record<string,unknown>):Promise<any>; validateLinguisticCorpus(payload:Record<string,unknown>):Promise<any>; createLinguisticCorpus(payload:Record<string,unknown>):Promise<any>; createLanguageAuthority(payload:Record<string,unknown>):Promise<any>; createLanguageResolutionCase(payload:Record<string,unknown>):Promise<any>; createLanguageResolutionDecision(id:string,payload:Record<string,unknown>):Promise<any>; validateLanguageAlignment(payload:Record<string,unknown>):Promise<any>; createLanguageAlignment(payload:Record<string,unknown>):Promise<any>;
  provenance():Promise<any>; provenanceReadiness():Promise<any>; recordProvenance(id:string,options?:{versionLimit?:number}):Promise<any>; citations(id:string,options?:{direction?:string,limit?:number}):Promise<any>; evidenceGraph(id:string,options?:{depth?:number,limit?:number,includeCore?:boolean}):Promise<any>; researchGraph():Promise<any>; researchGraphReadiness():Promise<any>; researchGraphNeighborhood(id:string,options?:{depth?:number,limit?:number,includeCore?:boolean,edgeFamilies?:string}):Promise<any>; researchGraphSummary(id:string,options?:{depth?:number,limit?:number,includeCore?:boolean}):Promise<any>; researchGraphPath(payload:Record<string,unknown>):Promise<any>; createCitation(payload:Record<string,unknown>):Promise<any>; importCitations(id:string):Promise<any>; citationCoreHandoff(payload:Record<string,unknown>):Promise<any>;
  retrieval():Promise<any>; retrievalReadiness():Promise<any>; retrievalFacets():Promise<any>; retrievalSearch(q?:string,options?:Record<string,unknown>):Promise<any>; retrievalPlan(payload:Record<string,unknown>):Promise<any>; retrievalSearchAdvanced(payload:Record<string,unknown>):Promise<any>;
  advancedDiscovery():Promise<any>; advancedDiscoveryReadiness():Promise<any>; advancedDiscoveryPlan(payload:Record<string,unknown>):Promise<any>; advancedDiscoverySearch(payload:Record<string,unknown>):Promise<any>; projectAdvancedDiscoverySearch(projectId:string,payload:Record<string,unknown>):Promise<any>;
  researchState():Promise<any>; researchStateReadiness():Promise<any>; researchStateForOwner(id:string):Promise<any>; createResearchProject(payload:Record<string,unknown>):Promise<any>; addProjectReference(projectId:string,payload:Record<string,unknown>):Promise<any>; createSourceBundle(projectId:string,payload:Record<string,unknown>):Promise<any>; saveSearch(payload:Record<string,unknown>):Promise<any>; saveWatchlist(payload:Record<string,unknown>):Promise<any>; enqueueResearch(payload:Record<string,unknown>):Promise<any>; createCollection(payload:Record<string,unknown>):Promise<any>; addCollectionItem(collectionId:string,payload:Record<string,unknown>):Promise<any>;
  ingestion():Promise<any>; ingestionReadiness():Promise<any>; normalizeIngestion(payload:Record<string,unknown>):Promise<any>; ingestSourceRecords(payload:Record<string,unknown>):Promise<any>; sourceIngestionState(sourceKey:string):Promise<any>;
  search(q?:string,filters?:Record<string,unknown>):Promise<any>; record(id:string,options?:{includeBody?:boolean}):Promise<any>; stats():Promise<any>; integrations():Promise<any>;
  submitResearchJob(payload:Record<string,unknown>):Promise<any>; product(key:string):ProductAdapter; researchLibrarian():ProductAdapter; workspace():ProductAdapter; researchLab():ProductAdapter; workbench():ProductAdapter; decisionStudio():ProductAdapter; siteIntelligence():ProductAdapter;
}
