<?php if (!defined('ABSPATH')) exit; ?>
<div class="wrap sc-library-planning-admin">
    <div class="sc-library-planning-admin__head">
        <div><p class="sc-library-planning-eyebrow"><?php esc_html_e('Sustainable Catalyst Library', 'sustainable-catalyst-library'); ?></p><h1><?php echo esc_html($page_title); ?></h1><p><?php esc_html_e('Measure workload, publication velocity, planning completeness, release risk, and dependency health across the Content Planner.', 'sustainable-catalyst-library'); ?></p></div>
        <div class="sc-library-planning-admin__actions"><a class="button button-primary" href="<?php echo esc_url(admin_url('post-new.php?post_type=' . SC_Library_Planner::POST_TYPE)); ?>"><?php esc_html_e('Add planned content', 'sustainable-catalyst-library'); ?></a><a class="button" href="<?php echo esc_url(admin_url('admin.php?page=sc-library-release-coordination')); ?>"><?php esc_html_e('Release coordination', 'sustainable-catalyst-library'); ?></a><button class="button" type="button" onclick="window.print()"><?php esc_html_e('Print report', 'sustainable-catalyst-library'); ?></button><a class="button" href="<?php echo esc_url($export_csv); ?>">CSV</a><a class="button" href="<?php echo esc_url($export_json); ?>">JSON</a></div>
    </div>
    <section class="sc-library-planning-metrics">
        <?php foreach ([
            'total_plans' => __('Total plans', 'sustainable-catalyst-library'), 'active' => __('Active', 'sustainable-catalyst-library'), 'completed' => __('Completed', 'sustainable-catalyst-library'),
            'blocked' => __('Blocked', 'sustainable-catalyst-library'), 'overdue' => __('Overdue', 'sustainable-catalyst-library'), 'unscheduled' => __('No release window', 'sustainable-catalyst-library'),
            'due_30_days' => __('Due in 30 days', 'sustainable-catalyst-library'), 'published_30_days' => __('Published in 30 days', 'sustainable-catalyst-library'),
            'estimated_effort' => __('Estimated effort', 'sustainable-catalyst-library'), 'average_completeness' => __('Average completeness', 'sustainable-catalyst-library'),
        ] as $key => $label) : ?><div class="sc-library-planning-metric"><span><?php echo esc_html($label); ?></span><strong><?php $metric_value = $key === 'estimated_effort' ? ($analytics['metrics']['estimated_effort_display'] ?? '0') : ($analytics['metrics'][$key] ?? 0); echo esc_html((string) $metric_value); ?><?php echo $key === 'average_completeness' ? '%' : ''; ?></strong></div><?php endforeach; ?>
    </section>
    <div class="sc-library-planning-summary-grid">
        <section class="card"><h2><?php esc_html_e('Timing performance', 'sustainable-catalyst-library'); ?></h2><dl><div><dt><?php esc_html_e('On-time rate', 'sustainable-catalyst-library'); ?></dt><dd><?php echo $analytics['metrics']['on_time_rate'] === null ? '—' : esc_html((string) $analytics['metrics']['on_time_rate']) . '%'; ?></dd></div><div><dt><?php esc_html_e('Average variance', 'sustainable-catalyst-library'); ?></dt><dd><?php echo $analytics['metrics']['average_variance_days'] === null ? '—' : esc_html((string) $analytics['metrics']['average_variance_days']) . ' days'; ?></dd></div><div><dt><?php esc_html_e('Published in 90 days', 'sustainable-catalyst-library'); ?></dt><dd><?php echo esc_html((string) $analytics['metrics']['published_90_days']); ?></dd></div></dl></section>
        <section class="card"><h2><?php esc_html_e('Dependency health', 'sustainable-catalyst-library'); ?></h2><dl><?php foreach ($analytics['dependency_summary'] as $key => $value) : ?><div><dt><?php echo esc_html(ucwords(str_replace('_', ' ', $key))); ?></dt><dd><?php echo esc_html((string) $value); ?></dd></div><?php endforeach; ?></dl></section>
        <section class="card"><h2><?php esc_html_e('Release health', 'sustainable-catalyst-library'); ?></h2><dl><?php foreach ($analytics['release_summary'] as $key => $value) : ?><div><dt><?php echo esc_html(ucwords(str_replace('_', ' ', $key))); ?></dt><dd><?php echo esc_html((string) $value); ?></dd></div><?php endforeach; ?></dl></section>
    </div>
    <div class="sc-library-planning-summary-grid">
        <section class="card"><h2><?php esc_html_e('Documentation coverage', 'sustainable-catalyst-library'); ?></h2><dl><?php foreach ([
            'total' => __('Documentation records', 'sustainable-catalyst-library'),
            'authority_coverage_percent' => __('Authority coverage', 'sustainable-catalyst-library'),
            'responsible_coverage_percent' => __('Responsible-area coverage', 'sustainable-catalyst-library'),
            'review_coverage_percent' => __('Review coverage', 'sustainable-catalyst-library'),
            'overdue_review' => __('Overdue reviews', 'sustainable-catalyst-library'),
        ] as $key => $label) : ?><div><dt><?php echo esc_html($label); ?></dt><dd><?php echo esc_html((string) ($analytics['documentation_coverage'][$key] ?? 0)); ?><?php echo str_contains($key, 'percent') ? '%' : ''; ?></dd></div><?php endforeach; ?></dl></section>
        <section class="card sc-library-planning-summary-grid__wide"><h2><?php esc_html_e('Knowledge-area gap analysis', 'sustainable-catalyst-library'); ?></h2><table class="widefat striped"><thead><tr><th><?php esc_html_e('Area', 'sustainable-catalyst-library'); ?></th><th><?php esc_html_e('Published/current', 'sustainable-catalyst-library'); ?></th><th><?php esc_html_e('Active plans', 'sustainable-catalyst-library'); ?></th><th><?php esc_html_e('Planned effort', 'sustainable-catalyst-library'); ?></th></tr></thead><tbody><?php foreach (array_slice($analytics['knowledge_gap_analysis'], 0, 12) as $gap) : ?><tr><td><?php echo esc_html($gap['area']); ?></td><td><?php echo esc_html((string) $gap['published']); ?></td><td><?php echo esc_html((string) $gap['active_plans']); ?></td><td><?php echo esc_html((string) $gap['planned_effort']); ?></td></tr><?php endforeach; ?></tbody></table></section>
    </div>
    <?php
    $tables = [
        __('By area', 'sustainable-catalyst-library') => $analytics['by_area'],
        __('By product', 'sustainable-catalyst-library') => $analytics['by_product'],
        __('By responsible owner', 'sustainable-catalyst-library') => $analytics['by_responsible'],
        __('By release group', 'sustainable-catalyst-library') => $analytics['by_release_group'],
    ];
    foreach ($tables as $heading => $rows) : ?>
        <section class="sc-library-planning-table-section"><h2><?php echo esc_html($heading); ?></h2><table class="widefat striped"><thead><tr><th><?php esc_html_e('Group', 'sustainable-catalyst-library'); ?></th><th><?php esc_html_e('Count', 'sustainable-catalyst-library'); ?></th><th><?php esc_html_e('Active', 'sustainable-catalyst-library'); ?></th><th><?php esc_html_e('Completed', 'sustainable-catalyst-library'); ?></th><th><?php esc_html_e('Blocked', 'sustainable-catalyst-library'); ?></th><th><?php esc_html_e('Overdue', 'sustainable-catalyst-library'); ?></th><th><?php esc_html_e('Effort', 'sustainable-catalyst-library'); ?></th><th><?php esc_html_e('Avg. progress', 'sustainable-catalyst-library'); ?></th></tr></thead><tbody><?php if (!$rows) : ?><tr><td colspan="8"><?php esc_html_e('No records found.', 'sustainable-catalyst-library'); ?></td></tr><?php endif; ?><?php foreach ($rows as $row) : ?><tr><td><?php echo esc_html($row['label']); ?></td><td><?php echo esc_html((string) $row['count']); ?></td><td><?php echo esc_html((string) $row['active']); ?></td><td><?php echo esc_html((string) $row['completed']); ?></td><td><?php echo esc_html((string) $row['blocked']); ?></td><td><?php echo esc_html((string) $row['overdue']); ?></td><td><?php echo esc_html((string) $row['effort_display']); ?></td><td><?php echo esc_html((string) $row['average_progress']); ?>%</td></tr><?php endforeach; ?></tbody></table></section>
    <?php endforeach; ?>
    <section class="sc-library-planning-table-section"><h2><?php esc_html_e('Coverage gaps', 'sustainable-catalyst-library'); ?></h2><p><?php esc_html_e('These are planning records missing fields needed for clear coordination and reliable public roadmaps.', 'sustainable-catalyst-library'); ?></p><table class="widefat striped"><thead><tr><th><?php esc_html_e('Plan', 'sustainable-catalyst-library'); ?></th><th><?php esc_html_e('Gap', 'sustainable-catalyst-library'); ?></th></tr></thead><tbody><?php if (!$analytics['coverage_gaps']) : ?><tr><td colspan="2"><?php esc_html_e('No major coverage gaps were detected.', 'sustainable-catalyst-library'); ?></td></tr><?php endif; ?><?php foreach ($analytics['coverage_gaps'] as $gap) : ?><tr><td><a href="<?php echo esc_url($gap['url']); ?>"><?php echo esc_html($gap['title']); ?></a></td><td><?php echo esc_html($gap['message']); ?></td></tr><?php endforeach; ?></tbody></table></section>
    <?php if ($graph['cycles']) : ?><section class="notice notice-error inline"><h2><?php esc_html_e('Dependency cycles', 'sustainable-catalyst-library'); ?></h2><p><?php esc_html_e('Circular dependencies can prevent every item in the chain from becoming ready.', 'sustainable-catalyst-library'); ?></p><ul><?php foreach ($graph['cycles'] as $cycle) : ?><li><?php echo esc_html(implode(' → ', array_map('strval', $cycle))); ?></li><?php endforeach; ?></ul></section><?php endif; ?>
</div>
