from __future__ import annotations
import hashlib, hmac, json, time
from dataclasses import dataclass
from typing import Any
from urllib import error, parse, request

PRODUCT_KEYS = (
    "research-librarian", "workspace", "research-lab",
    "workbench", "decision-studio", "site-intelligence",
)


def _canonical_body(payload: Any | None) -> bytes:
    if payload is None:
        return b""
    return json.dumps(payload, separators=(",", ":"), ensure_ascii=False).encode("utf-8")


def sign_request(method: str, path: str, timestamp: str, body: bytes, key: str) -> str:
    body_hash = hashlib.sha256(body).hexdigest()
    base = f"{method.upper()}\n{path}\n{timestamp}\n{body_hash}".encode("utf-8")
    return hmac.new(key.encode("utf-8"), base, hashlib.sha256).hexdigest()


class LibraryError(RuntimeError):
    def __init__(self, message: str, *, status: int | None = None, code: str | None = None, details: Any = None):
        super().__init__(message)
        self.status = status
        self.code = code
        self.details = details


@dataclass(frozen=True)
class ProductAdapter:
    client: "LibraryClient"
    product_key: str

    def contract(self) -> dict[str, Any]:
        return self.client.get(f"/integrations/{parse.quote(self.product_key)}")

    def validate_exchange(self, payload: dict[str, Any]) -> dict[str, Any]:
        return self.client.post_signed(f"/integrations/{parse.quote(self.product_key)}/exchange/validate", payload)


class LibraryClient:
    def __init__(self, base_url: str, *, api_key: str | None = None, timeout: float = 20.0, max_retries: int = 2):
        self.base_url = base_url.rstrip("/")
        if not self.base_url.endswith("/api/library/v1"):
            self.base_url += "/api/library/v1"
        self.api_key = api_key
        self.timeout = float(timeout)
        self.max_retries = max(0, int(max_retries))

    def _decode_error(self, exc: error.HTTPError) -> LibraryError:
        try:
            payload = json.loads(exc.read().decode("utf-8"))
            detail = payload.get("error") or payload.get("detail") or payload
        except Exception:
            detail = None
        if isinstance(detail, dict):
            inner = detail.get("error") if isinstance(detail.get("error"), dict) else detail
            return LibraryError(str(inner.get("message") or exc.reason), status=exc.code, code=inner.get("code"), details=inner.get("details"))
        return LibraryError(str(detail or exc.reason), status=exc.code)

    def request(self, method: str, path: str, *, query: dict[str, Any] | None = None, payload: Any | None = None, signed: bool = False) -> Any:
        path = "/" + path.lstrip("/")
        url = self.base_url + path
        if query:
            q = {k: v for k, v in query.items() if v is not None}
            if q:
                url += "?" + parse.urlencode(q, doseq=True)
        body = _canonical_body(payload)
        headers = {"Accept": "application/json"}
        if payload is not None:
            headers["Content-Type"] = "application/json"
        if signed:
            if not self.api_key:
                raise LibraryError("api_key is required for signed requests")
            ts = str(int(time.time()))
            headers.update({
                "Authorization": f"Bearer {self.api_key}",
                "X-SC-Timestamp": ts,
                "X-SC-Signature": sign_request(method, path, ts, body, self.api_key),
            })
        retryable = {429, 502, 503, 504}
        for attempt in range(self.max_retries + 1):
            try:
                req = request.Request(url, data=body if payload is not None else None, headers=headers, method=method.upper())
                with request.urlopen(req, timeout=self.timeout) as resp:
                    raw = resp.read()
                    return json.loads(raw.decode("utf-8")) if raw else None
            except error.HTTPError as exc:
                if exc.code in retryable and attempt < self.max_retries:
                    time.sleep(min(0.25 * (2 ** attempt), 1.0))
                    continue
                raise self._decode_error(exc) from exc
            except error.URLError as exc:
                if attempt < self.max_retries:
                    time.sleep(min(0.25 * (2 ** attempt), 1.0))
                    continue
                raise LibraryError(str(exc.reason)) from exc

    def get(self, path: str, query: dict[str, Any] | None = None) -> Any:
        return self.request("GET", path, query=query)

    def post(self, path: str, payload: Any) -> Any:
        return self.request("POST", path, payload=payload)

    def get_signed(self, path: str, query: dict[str, Any] | None = None) -> Any:
        return self.request("GET", path, query=query, signed=True)

    def post_signed(self, path: str, payload: Any) -> Any:
        return self.request("POST", path, payload=payload, signed=True)

    def delete_signed(self, path: str) -> Any:
        return self.request("DELETE", path, signed=True)

    def health(self): return self.get("/health")
    def readiness(self): return self.get("/readiness")
    def service(self): return self.get("/service")
    def capabilities(self): return self.get("/capabilities")
    def routes(self): return self.get("/routes")
    def client_framework(self): return self.get("/client-framework")
    def catalog(self): return self.get("/catalog")
    def catalog_readiness(self): return self.get("/catalog/readiness")
    def research_state(self): return self.get("/research-state")
    def research_state_readiness(self): return self.get("/research-state/readiness")
    def ingestion(self): return self.get("/ingestion")
    def ingestion_readiness(self): return self.get("/ingestion/readiness")
    def retrieval(self): return self.get("/retrieval")
    def retrieval_readiness(self): return self.get("/retrieval/readiness")
    def advanced_discovery(self): return self.get("/discovery")
    def advanced_discovery_readiness(self): return self.get("/discovery/readiness")
    def advanced_discovery_plan(self, payload: dict[str, Any]): return self.post("/discovery/plan", payload)
    def advanced_discovery_search(self, payload: dict[str, Any]): return self.post("/discovery/search", payload)
    def project_advanced_discovery_search(self, project_id: str, payload: dict[str, Any]): return self.post("/discovery/projects/" + parse.quote(project_id, safe="") + "/search", payload)
    def provenance(self): return self.get("/provenance")
    def provenance_readiness(self): return self.get("/provenance/readiness")
    def saved_workspaces(self): return self.get("/saved-workspaces")
    def saved_workspaces_readiness(self): return self.get("/saved-workspaces/readiness")
    def navigation(self): return self.get("/navigation")
    def navigation_readiness(self): return self.get("/navigation/readiness")
    def navigation_bootstrap(self): return self.get("/navigation/bootstrap")
    def resolve_navigation(self, path: str): return self.get("/navigation/resolve", {"path": path})
    def research_interface(self): return self.get("/research-interface")
    def research_interface_readiness(self): return self.get("/research-interface/readiness")
    def research_interface_bootstrap(self): return self.get("/research-interface/bootstrap")
    def research_interface_search(self, q: str = "", **options): return self.get("/research-interface/search", {"q": q, **options})
    def research_interface_record(self, record_id: str, *, include_body: bool = True, version_limit: int = 12, evidence_depth: int = 1, evidence_limit: int = 120): return self.get("/research-interface/records/" + parse.quote(record_id, safe=""), {"include_body": str(include_body).lower(), "version_limit": version_limit, "evidence_depth": evidence_depth, "evidence_limit": evidence_limit})
    def research_interface_owner_state(self, owner_identity_id: str): return self.get_signed("/admin/research-interface/owners/" + parse.quote(owner_identity_id, safe=""))
    def library_product(self): return self.get("/product")
    def library_product_readiness(self): return self.get("/product/readiness")
    def library_product_release(self): return self.get("/product/release")
    def independent_application(self): return self.get("/independent-application")
    def independent_application_readiness(self): return self.get("/independent-application/readiness")
    def independent_application_certification(self): return self.get("/independent-application/certification")
    def certify_independent_application(self, payload: dict[str, Any] | None = None): return self.post_signed("/admin/independent-application/certify", payload or {})
    def wordpress_adapter(self): return self.get("/wordpress-adapter")
    def wordpress_adapter_readiness(self): return self.get("/wordpress-adapter/readiness")
    def wordpress_adapter_consolidation(self): return self.get("/wordpress-adapter/consolidation")
    def certify_wordpress_adapter_consolidation(self, payload: dict[str, Any]): return self.post_signed("/admin/wordpress-adapter/consolidation/certify", payload)
    def workflows(self): return self.get("/workflows")
    def workflows_readiness(self): return self.get("/workflows/readiness")
    def validate_workflow_control(self, payload: dict[str, Any]): return self.post_signed("/admin/workflows/validate", payload)
    def workflow_jobs(self, **filters): return self.get_signed("/admin/workflows/jobs", filters or None)
    def workflow_job(self, job_id: str): return self.get_signed("/admin/workflows/jobs/" + parse.quote(job_id, safe=""))
    def submit_workflow_job(self, payload: dict[str, Any]): return self.post_signed("/admin/workflows/jobs", payload)
    def cancel_workflow_job(self, job_id: str, reason: str = ""): return self.post_signed("/admin/workflows/jobs/" + parse.quote(job_id, safe="") + "/cancel", {"reason": reason})
    def workflow_workers(self): return self.get_signed("/admin/workflows/workers")
    def workflow_dead_letters(self, *, state: str = "open", limit: int = 100): return self.get_signed("/admin/workflows/dead-letters", {"state": state, "limit": limit})
    def recover_workflow_leases(self, limit: int = 100): return self.post_signed("/admin/workflows/recover-expired-leases", {"limit": limit})
    def validate_workflow_pipeline(self, payload: dict[str, Any]): return self.post_signed("/admin/workflows/pipelines/validate", payload)
    def create_workflow_pipeline(self, payload: dict[str, Any]): return self.post_signed("/admin/workflows/pipelines", payload)
    def workflow_pipeline(self, run_id: str): return self.get_signed("/admin/workflows/pipelines/" + parse.quote(run_id, safe=""))
    def resume_workflow_pipeline(self, run_id: str): return self.post_signed("/admin/workflows/pipelines/" + parse.quote(run_id, safe="") + "/resume", {})
    def federation(self, **filters): return self.get("/federation/sources", filters or None)
    def federation_readiness(self): return self.get("/federation/readiness")
    def federation_source(self, source_id: str): return self.get("/federation/sources/" + parse.quote(source_id, safe=""))
    def federation_connector(self, connector_id: str): return self.get("/federation/connectors/" + parse.quote(connector_id, safe=""))
    def federation_connector_status(self, connector_id: str): return self.get("/federation/connectors/" + parse.quote(connector_id, safe="") + "/status")
    def federation_collections(self): return self.get("/federation/collections")
    def federation_certification(self): return self.get("/federation/certification")
    def global_federation(self): return self.get("/federation/global")
    def global_federation_readiness(self): return self.get("/federation/global/readiness")
    def global_federation_lenses(self): return self.get("/federation/global/lenses")
    def global_federation_source(self, source_id: str): return self.get("/federation/global/sources/" + parse.quote(source_id, safe=""))
    def plan_global_federation(self, payload: dict[str, Any]): return self.post("/federation/global/plan", payload)
    def global_federated_discovery(self, payload: dict[str, Any]): return self.post("/federation/global/discover", payload)
    def validate_federation_connector(self, payload: dict[str, Any]): return self.post_signed("/admin/federation/connectors/validate", payload)
    def plan_federation_connector(self, payload: dict[str, Any]): return self.post_signed("/admin/federation/plan", payload)
    def validate_federation_certification(self, payload: dict[str, Any]): return self.post_signed("/admin/federation/certifications/validate", payload)
    def create_federation_certification(self, payload: dict[str, Any] | None = None): return self.post_signed("/admin/federation/certifications", payload or {})
    def reproducibility(self): return self.get("/reproducibility")
    def reproducibility_readiness(self): return self.get("/reproducibility/readiness")
    def runtime_reproducibility_status(self): return self.get("/reproducibility/runtime")
    def research_package(self, package_id: str, *, include_manifest: bool = True): return self.get("/reproducibility/packages/" + parse.quote(package_id, safe=""), {"include_manifest": str(include_manifest).lower()})
    def validate_research_package(self, payload: dict[str, Any]): return self.post_signed("/admin/reproducibility/packages/validate", payload)
    def create_research_package(self, payload: dict[str, Any]): return self.post_signed("/admin/reproducibility/packages", payload)
    def verify_research_package(self, package_id: str, payload: dict[str, Any] | None = None): return self.post_signed("/admin/reproducibility/packages/" + parse.quote(package_id, safe="") + "/verify", payload or {})
    def language(self): return self.get("/language")
    def language_readiness(self): return self.get("/language/readiness")
    def language_capture(self, capture_id: str, *, include_text: bool=False): return self.get("/language/captures/" + parse.quote(capture_id,safe=""), {"include_text":str(include_text).lower()})
    def language_derivation(self, run_id: str, *, include_text: bool=False): return self.get("/language/derivations/" + parse.quote(run_id,safe=""), {"include_text":str(include_text).lower()})
    def linguistic_corpus(self, corpus_id: str, *, include_tokens: bool=False): return self.get("/language/corpora/" + parse.quote(corpus_id,safe=""), {"include_tokens":str(include_tokens).lower()})
    def linguistic_kwic(self, corpus_id: str, q: str, **options): return self.get("/language/corpora/" + parse.quote(corpus_id,safe="") + "/kwic", {"q":q, **options})
    def language_resolution_case(self, case_id: str): return self.get("/language/entity-resolution/" + parse.quote(case_id,safe=""))
    def language_alignment(self, matrix_id: str): return self.get("/language/alignments/" + parse.quote(matrix_id,safe=""))
    def scientific_document_intelligence(self, record_id: str): return self.get("/language/documents/" + parse.quote(record_id,safe="") + "/intelligence")
    def validate_language_capture(self, payload: dict[str, Any]): return self.post_signed("/admin/language/captures/validate",payload)
    def create_language_capture(self, payload: dict[str, Any]): return self.post_signed("/admin/language/captures",payload)
    def validate_language_derivation(self, payload: dict[str, Any]): return self.post_signed("/admin/language/derivations/validate",payload)
    def create_language_derivation(self, payload: dict[str, Any]): return self.post_signed("/admin/language/derivations",payload)
    def validate_linguistic_corpus(self, payload: dict[str, Any]): return self.post_signed("/admin/language/corpora/validate",payload)
    def create_linguistic_corpus(self, payload: dict[str, Any]): return self.post_signed("/admin/language/corpora",payload)
    def create_language_authority(self, payload: dict[str, Any]): return self.post_signed("/admin/language/authorities",payload)
    def create_language_resolution_case(self, payload: dict[str, Any]): return self.post_signed("/admin/language/entity-resolution/cases",payload)
    def create_language_resolution_decision(self, case_id: str, payload: dict[str, Any]): return self.post_signed("/admin/language/entity-resolution/" + parse.quote(case_id,safe="") + "/decisions",payload)
    def validate_language_alignment(self, payload: dict[str, Any]): return self.post_signed("/admin/language/alignments/validate",payload)
    def create_language_alignment(self, payload: dict[str, Any]): return self.post_signed("/admin/language/alignments",payload)
    def record_provenance(self, record_id: str, *, version_limit: int = 25): return self.get("/provenance/records/" + parse.quote(record_id, safe=""), {"version_limit": version_limit})
    def citations(self, record_id: str, *, direction: str = "both", limit: int = 100): return self.get("/citations/" + parse.quote(record_id, safe=""), {"direction": direction, "limit": limit})
    def evidence_graph(self, record_id: str, *, depth: int = 2, limit: int = 250, include_core: bool = True): return self.get("/evidence-graph/" + parse.quote(record_id, safe=""), {"depth": depth, "limit": limit, "include_core": str(include_core).lower()})
    def research_graph(self): return self.get("/research-graph")
    def research_graph_readiness(self): return self.get("/research-graph/readiness")
    def research_graph_neighborhood(self, record_id: str, *, depth: int = 2, limit: int = 250, include_core: bool = True, edge_families: str = ""): return self.get("/research-graph/records/" + parse.quote(record_id, safe="") + "/neighborhood", {"depth": depth, "limit": limit, "include_core": str(include_core).lower(), "edge_families": edge_families})
    def research_graph_summary(self, record_id: str, *, depth: int = 1, limit: int = 250, include_core: bool = True): return self.get("/research-graph/records/" + parse.quote(record_id, safe="") + "/summary", {"depth": depth, "limit": limit, "include_core": str(include_core).lower()})
    def research_graph_path(self, payload: dict[str, Any]): return self.post("/research-graph/path", payload)
    def living_research(self): return self.get("/living-research")
    def living_research_readiness(self): return self.get("/living-research/readiness")
    def living_project_brief(self, project_id: str, *, include_graph: bool = False): return self.get("/living-research/projects/" + parse.quote(project_id, safe="") + "/brief", {"include_graph": str(include_graph).lower()})
    def living_collection(self, collection_id: str): return self.get("/living-research/collections/" + parse.quote(collection_id, safe=""))
    def living_collection_refresh(self, collection_id: str, payload: dict[str, Any] | None = None): return self.post("/living-research/collections/" + parse.quote(collection_id, safe="") + "/refresh", payload or {})
    def living_collection_apply(self, collection_id: str, payload: dict[str, Any]): return self.post("/living-research/collections/" + parse.quote(collection_id, safe="") + "/apply", payload)
    def structured_evidence(self): return self.get("/structured-evidence")
    def structured_evidence_readiness(self): return self.get("/structured-evidence/readiness")
    def structured_evidence_schemas(self): return self.get("/structured-evidence/schemas")
    def build_structured_dataset(self, payload: dict[str, Any]): return self.post("/structured-evidence/datasets", payload)
    def build_structured_table(self, payload: dict[str, Any]): return self.post("/structured-evidence/tables", payload)
    def build_structured_evidence(self, payload: dict[str, Any]): return self.post("/structured-evidence/objects", payload)
    def validate_structured_evidence(self, payload: dict[str, Any]): return self.post("/structured-evidence/validate", payload)
    def scientific_literature(self): return self.get("/scientific-literature")
    def scientific_literature_readiness(self): return self.get("/scientific-literature/readiness")
    def scientific_literature_schemas(self): return self.get("/scientific-literature/schemas")
    def normalize_scientific_publication(self, payload: dict[str, Any]): return self.post("/scientific-literature/publications/normalize", payload)
    def analyze_scientific_publication(self, payload: dict[str, Any]): return self.post("/scientific-literature/publications/analyze", payload)
    def analyze_scientific_literature_set(self, payload: dict[str, Any]): return self.post("/scientific-literature/sets/analyze", payload)
    def analyze_scientific_literature_review(self, payload: dict[str, Any]): return self.post("/scientific-literature/reviews/analyze", payload)
    def validate_scientific_publication(self, payload: dict[str, Any]): return self.post("/scientific-literature/validate", payload)
    def research_package_publishing(self): return self.get("/research-package-publishing")
    def research_package_publishing_readiness(self): return self.get("/research-package-publishing/readiness")
    def research_package_export_formats(self): return self.get("/research-package-publishing/formats")
    def preview_research_package_export(self, payload: dict[str, Any]): return self.post("/research-package-publishing/preview", payload)
    def build_research_package_export(self, payload: dict[str, Any]): return self.post("/research-package-publishing/export", payload)
    def validate_research_package_export(self, payload: dict[str, Any]): return self.post("/research-package-publishing/validate", payload)
    def persist_research_package_export(self, payload: dict[str, Any]): return self.post_signed("/admin/research-package-publishing/persist", payload)
    def institutional_repositories(self): return self.get("/institutional-repositories")
    def institutional_repositories_readiness(self): return self.get("/institutional-repositories/readiness")
    def institutional_repository_schemas(self): return self.get("/institutional-repositories/schemas")
    def institutional_repository_profiles(self): return self.get("/institutional-repositories/repositories")
    def institutional_repository_profile(self, source_key: str): return self.get("/institutional-repositories/repositories/" + parse.quote(source_key, safe=""))
    def plan_institutional_repository_federation(self, payload: dict[str, Any]): return self.post("/institutional-repositories/plan", payload)
    def search_institutional_repositories(self, payload: dict[str, Any]): return self.post("/institutional-repositories/search", payload)
    def institutional_repository_handoff(self, payload: dict[str, Any]): return self.post("/institutional-repositories/handoff", payload)
    def historical_archives(self): return self.get("/historical-archives")
    def historical_archives_readiness(self): return self.get("/historical-archives/readiness")
    def historical_archive_schemas(self): return self.get("/historical-archives/schemas")
    def historical_source_types(self): return self.get("/historical-archives/source-types")
    def normalize_historical_date(self, payload: dict[str, Any]): return self.post("/historical-archives/dates/normalize", payload)
    def normalize_primary_source(self, payload: dict[str, Any]): return self.post("/historical-archives/primary-sources/normalize", payload)
    def primary_source_provenance(self, payload: dict[str, Any]): return self.post("/historical-archives/primary-sources/provenance", payload)
    def analyze_primary_source(self, payload: dict[str, Any]): return self.post("/historical-archives/primary-sources/analyze", payload)
    def compare_primary_sources(self, payload: dict[str, Any]): return self.post("/historical-archives/primary-sources/compare", payload)
    def historical_archive_search_plan(self, payload: dict[str, Any]): return self.post("/historical-archives/search/plan", payload)
    def historical_primary_source_timeline(self, payload: dict[str, Any]): return self.post("/historical-archives/timeline", payload)
    def build_primary_source_packet(self, payload: dict[str, Any]): return self.post("/historical-archives/packets", payload)
    def historical_primary_source_handoff(self, payload: dict[str, Any]): return self.post("/historical-archives/handoff", payload)
    def historical_archives_workspace(self): return self.get("/historical-archives/workspace")
    def historical_archives_workspace_readiness(self): return self.get("/historical-archives/workspace/readiness")
    def historical_archives_workspace_bootstrap(self): return self.get("/historical-archives/workspace/bootstrap")
    def historical_archives_workspace_search(self, payload: dict[str, Any]): return self.post("/historical-archives/workspace/search", payload)
    def historical_archives_source_workspace(self, payload: dict[str, Any]): return self.post("/historical-archives/workspace/source", payload)
    def historical_archives_compare_workspace(self, payload: dict[str, Any]): return self.post("/historical-archives/workspace/compare", payload)
    def historical_archives_timeline_workspace(self, payload: dict[str, Any]): return self.post("/historical-archives/workspace/timeline", payload)
    def historical_archives_packet_workspace(self, payload: dict[str, Any]): return self.post("/historical-archives/workspace/packet", payload)
    def historical_archives_handoff_workspace(self, payload: dict[str, Any]): return self.post("/historical-archives/workspace/handoff", payload)
    def primary_source_criticism(self): return self.get("/historical-archives/source-criticism")
    def primary_source_criticism_readiness(self): return self.get("/historical-archives/source-criticism/readiness")
    def primary_source_criticism_bootstrap(self): return self.get("/historical-archives/source-criticism/bootstrap")
    def analyze_primary_source_criticism(self, payload: dict[str, Any]): return self.post("/historical-archives/source-criticism/analyze", payload)
    def primary_source_criticism_matrix(self, payload: dict[str, Any]): return self.post("/historical-archives/source-criticism/matrix", payload)
    def primary_source_corroboration_ledger(self, payload: dict[str, Any]): return self.post("/historical-archives/source-criticism/corroboration", payload)
    def historical_event_timeline(self): return self.get("/historical-archives/timeline-workspace")
    def historical_event_timeline_readiness(self): return self.get("/historical-archives/timeline-workspace/readiness")
    def historical_event_timeline_bootstrap(self): return self.get("/historical-archives/timeline-workspace/bootstrap")
    def normalize_historical_event(self, payload: dict[str, Any]): return self.post("/historical-archives/timeline-workspace/events/normalize", payload)
    def build_historical_event_timeline(self, payload: dict[str, Any]): return self.post("/historical-archives/timeline-workspace/build", payload)
    def historical_event_source_coverage(self, payload: dict[str, Any]): return self.post("/historical-archives/timeline-workspace/source-coverage", payload)
    def compare_historical_chronologies(self, payload: dict[str, Any]): return self.post("/historical-archives/timeline-workspace/compare", payload)
    def research_annotations(self): return self.get("/annotations")
    def research_annotations_readiness(self): return self.get("/annotations/readiness")
    def research_annotations_bootstrap(self): return self.get("/annotations/bootstrap")
    def normalize_research_annotation(self, payload: dict[str, Any]): return self.post("/annotations/normalize", payload)
    def normalize_annotation_relation(self, payload: dict[str, Any]): return self.post("/annotations/relations/normalize", payload)
    def build_scholarly_notebook(self, payload: dict[str, Any]): return self.post("/annotations/notebook", payload)
    def export_scholarly_notes(self, payload: dict[str, Any]): return self.post("/annotations/export", payload)
    def citation_workspace(self): return self.get("/citations/workspace")
    def citation_workspace_readiness(self): return self.get("/citations/workspace/readiness")
    def citation_workspace_bootstrap(self): return self.get("/citations/workspace/bootstrap")
    def normalize_bibliographic_item(self, payload: dict[str, Any]): return self.post("/citations/workspace/normalize", payload)
    def build_research_bibliography(self, payload: dict[str, Any]): return self.post("/citations/workspace/bibliography", payload)
    def analyze_bibliographic_duplicates(self, payload: dict[str, Any]): return self.post("/citations/workspace/duplicates", payload)
    def export_research_bibliography(self, payload: dict[str, Any]): return self.post("/citations/workspace/export", payload)
    def citation_authority_handoff_preview(self, payload: dict[str, Any]): return self.post("/citations/workspace/handoff-preview", payload)
    def corpus_workspace(self): return self.get("/corpus-workspace")
    def corpus_workspace_readiness(self): return self.get("/corpus-workspace/readiness")
    def corpus_workspace_bootstrap(self): return self.get("/corpus-workspace/bootstrap")
    def preview_computational_corpus(self, payload: dict[str, Any]): return self.post("/corpus-workspace/preview", payload)
    def computational_corpus_frequency(self, payload: dict[str, Any]): return self.post("/corpus-workspace/frequency", payload)
    def computational_corpus_kwic(self, payload: dict[str, Any]): return self.post("/corpus-workspace/kwic", payload)
    def computational_corpus_ngrams(self, payload: dict[str, Any]): return self.post("/corpus-workspace/ngrams", payload)
    def computational_corpus_cooccurrence(self, payload: dict[str, Any]): return self.post("/corpus-workspace/cooccurrence", payload)
    def export_computational_linguistics_analysis(self, payload: dict[str, Any]): return self.post("/corpus-workspace/export", payload)
    def computational_corpus_persistence_handoff_preview(self, payload: dict[str, Any]): return self.post("/corpus-workspace/persistence-handoff-preview", payload)
    def entity_place_workspace(self): return self.get("/entity-place-workspace")
    def entity_place_workspace_readiness(self): return self.get("/entity-place-workspace/readiness")
    def entity_place_workspace_bootstrap(self): return self.get("/entity-place-workspace/bootstrap")
    def preview_entity_authority(self, payload: dict[str, Any]): return self.post("/entity-place-workspace/authority-preview", payload)
    def preview_entity_resolution(self, payload: dict[str, Any]): return self.post("/entity-place-workspace/resolve-preview", payload)
    def historical_toponym_timeline(self, payload: dict[str, Any]): return self.post("/entity-place-workspace/toponym-timeline", payload)
    def entity_candidate_matrix(self, payload: dict[str, Any]): return self.post("/entity-place-workspace/candidate-matrix", payload)
    def preview_entity_resolution_decision(self, payload: dict[str, Any]): return self.post("/entity-place-workspace/decision-preview", payload)
    def entity_resolution_case(self, case_id: str): return self.get(f"/entity-place-workspace/cases/{case_id}")
    def export_entity_place_research(self, payload: dict[str, Any]): return self.post("/entity-place-workspace/export", payload)
    def entity_place_persistence_handoff_preview(self, payload: dict[str, Any]): return self.post("/entity-place-workspace/persistence-handoff-preview", payload)
    def research_synthesis(self): return self.get("/research-synthesis")
    def research_synthesis_readiness(self): return self.get("/research-synthesis/readiness")
    def research_synthesis_bootstrap(self): return self.get("/research-synthesis/bootstrap")
    def build_research_synthesis(self, payload: dict[str, Any]): return self.post("/research-synthesis/synthesize", payload)
    def research_synthesis_evidence_matrix(self, payload: dict[str, Any]): return self.post("/research-synthesis/evidence-matrix", payload)
    def research_synthesis_contradictions(self, payload: dict[str, Any]): return self.post("/research-synthesis/contradictions", payload)
    def research_synthesis_convergence(self, payload: dict[str, Any]): return self.post("/research-synthesis/convergence", payload)
    def research_synthesis_source_attribution(self, payload: dict[str, Any]): return self.post("/research-synthesis/source-attribution", payload)
    def research_synthesis_gaps(self, payload: dict[str, Any]): return self.post("/research-synthesis/gaps", payload)
    def export_research_synthesis(self, payload: dict[str, Any]): return self.post("/research-synthesis/export", payload)
    def research_synthesis_publishing_handoff_preview(self, payload: dict[str, Any]): return self.post("/research-synthesis/publishing-handoff-preview", payload)
    def research_investigation(self): return self.get("/research-investigation")
    def research_investigation_readiness(self): return self.get("/research-investigation/readiness")
    def research_investigation_bootstrap(self): return self.get("/research-investigation/bootstrap")
    def build_research_investigation(self, payload: dict[str, Any]): return self.post("/research-investigation/build", payload)
    def research_investigation_matrix(self, payload: dict[str, Any]): return self.post("/research-investigation/matrix", payload)
    def research_investigation_coverage(self, payload: dict[str, Any]): return self.post("/research-investigation/coverage", payload)
    def research_investigation_execution_plan(self, payload: dict[str, Any]): return self.post("/research-investigation/execution-plan", payload)
    def research_investigation_risk_register(self, payload: dict[str, Any]): return self.post("/research-investigation/risk-register", payload)
    def export_research_investigation(self, payload: dict[str, Any]): return self.post("/research-investigation/export", payload)
    def research_investigation_handoff_preview(self, payload: dict[str, Any]): return self.post("/research-investigation/handoff-preview", payload)
    def evidence_matrix(self): return self.get("/evidence-matrix")
    def evidence_matrix_readiness(self): return self.get("/evidence-matrix/readiness")
    def evidence_matrix_bootstrap(self): return self.get("/evidence-matrix/bootstrap")
    def build_claim_evidence_matrix(self, payload: dict[str, Any]): return self.post("/evidence-matrix/matrix", payload)
    def evidence_support_profiles(self, payload: dict[str, Any]): return self.post("/evidence-matrix/support-profiles", payload)
    def evidence_contradictions(self, payload: dict[str, Any]): return self.post("/evidence-matrix/contradictions", payload)
    def evidence_provenance_coverage(self, payload: dict[str, Any]): return self.post("/evidence-matrix/provenance-coverage", payload)
    def evidence_source_dependencies(self, payload: dict[str, Any]): return self.post("/evidence-matrix/source-dependencies", payload)
    def evidence_gaps(self, payload: dict[str, Any]): return self.post("/evidence-matrix/gaps", payload)
    def export_evidence_matrix_analysis(self, payload: dict[str, Any]): return self.post("/evidence-matrix/export", payload)
    def evidence_synthesis_handoff_preview(self, payload: dict[str, Any]): return self.post("/evidence-matrix/synthesis-handoff-preview", payload)
    def evidence_investigation_handoff_preview(self, payload: dict[str, Any]): return self.post("/evidence-matrix/investigation-handoff-preview", payload)
    def statistical_evidence(self): return self.get("/statistical-evidence")
    def statistical_evidence_readiness(self): return self.get("/statistical-evidence/readiness")
    def statistical_evidence_bootstrap(self): return self.get("/statistical-evidence/bootstrap")
    def discover_datasets(self, payload: dict[str, Any]): return self.post("/statistical-evidence/discover", payload)
    def statistical_dataset_profile(self, payload: dict[str, Any]): return self.post("/statistical-evidence/dataset-profile", payload)
    def statistical_evidence_table(self, payload: dict[str, Any]): return self.post("/statistical-evidence/statistical-table", payload)
    def statistical_uncertainty_audit(self, payload: dict[str, Any]): return self.post("/statistical-evidence/uncertainty-audit", payload)
    def statistical_evidence_gaps(self, payload: dict[str, Any]): return self.post("/statistical-evidence/gaps", payload)
    def statistical_evidence_matrix_handoff_preview(self, payload: dict[str, Any]): return self.post("/statistical-evidence/evidence-handoff-preview", payload)
    def statistical_investigation_handoff_preview(self, payload: dict[str, Any]): return self.post("/statistical-evidence/investigation-handoff-preview", payload)
    def export_statistical_evidence(self, payload: dict[str, Any]): return self.post("/statistical-evidence/export", payload)
    def geospatial_research(self): return self.get("/geospatial-research")
    def geospatial_research_readiness(self): return self.get("/geospatial-research/readiness")
    def geospatial_research_bootstrap(self): return self.get("/geospatial-research/bootstrap")
    def geospatial_inventory(self, payload: dict[str, Any]): return self.post("/geospatial-research/inventory", payload)
    def geospatial_relation_preview(self, payload: dict[str, Any]): return self.post("/geospatial-research/relation-preview", payload)
    def geospatial_coverage_audit(self, payload: dict[str, Any]): return self.post("/geospatial-research/coverage-audit", payload)
    def geospatial_temporal_validity(self, payload: dict[str, Any]): return self.post("/geospatial-research/temporal-validity", payload)
    def geospatial_evidence_handoff_preview(self, payload: dict[str, Any]): return self.post("/geospatial-research/evidence-handoff-preview", payload)
    def geospatial_investigation_handoff_preview(self, payload: dict[str, Any]): return self.post("/geospatial-research/investigation-handoff-preview", payload)
    def export_geospatial_research(self, payload: dict[str, Any]): return self.post("/geospatial-research/export", payload)
    def research_package_composer(self): return self.get("/research-package-composer")
    def research_package_composer_readiness(self): return self.get("/research-package-composer/readiness")
    def research_package_composer_bootstrap(self): return self.get("/research-package-composer/bootstrap")
    def compose_research_package(self, payload: dict[str, Any]): return self.post("/research-package-composer/compose", payload)
    def research_package_completeness_audit(self, payload: dict[str, Any]): return self.post("/research-package-composer/completeness-audit", payload)
    def research_package_provenance_audit(self, payload: dict[str, Any]): return self.post("/research-package-composer/provenance-audit", payload)
    def research_package_dependency_map(self, payload: dict[str, Any]): return self.post("/research-package-composer/dependency-map", payload)
    def research_package_composer_publishing_handoff_preview(self, payload: dict[str, Any]): return self.post("/research-package-composer/publishing-handoff-preview", payload)
    def research_package_composer_reproducibility_handoff_preview(self, payload: dict[str, Any]): return self.post("/research-package-composer/reproducibility-handoff-preview", payload)
    def export_research_package_composition(self, payload: dict[str, Any]): return self.post("/research-package-composer/export", payload)
    def research_publication_studio(self): return self.get("/research-publication")
    def research_publication_readiness(self): return self.get("/research-publication/readiness")
    def research_publication_bootstrap(self): return self.get("/research-publication/bootstrap")
    def build_research_publication_draft(self, payload: dict[str, Any]): return self.post("/research-publication/draft", payload)
    def research_publication_section_inventory(self, payload: dict[str, Any]): return self.post("/research-publication/section-inventory", payload)
    def research_publication_asset_inventory(self, payload: dict[str, Any]): return self.post("/research-publication/asset-inventory", payload)
    def research_publication_citation_inventory(self, payload: dict[str, Any]): return self.post("/research-publication/citation-inventory", payload)
    def research_publication_editorial_audit(self, payload: dict[str, Any]): return self.post("/research-publication/editorial-audit", payload)
    def research_publication_readiness_audit(self, payload: dict[str, Any]): return self.post("/research-publication/readiness-audit", payload)
    def research_publication_publishing_handoff_preview(self, payload: dict[str, Any]): return self.post("/research-publication/publishing-handoff-preview", payload)
    def export_research_publication_draft(self, payload: dict[str, Any]): return self.post("/research-publication/export", payload)
    def unified_research_knowledge_graph(self): return self.get("/research-knowledge-graph")
    def unified_research_knowledge_graph_readiness(self): return self.get("/research-knowledge-graph/readiness")
    def unified_research_knowledge_graph_bootstrap(self): return self.get("/research-knowledge-graph/bootstrap")
    def build_unified_research_knowledge_graph(self, payload: dict[str, Any]): return self.post("/research-knowledge-graph/build", payload)
    def validate_unified_research_knowledge_graph(self, payload: dict[str, Any]): return self.post("/research-knowledge-graph/validate", payload)
    def audit_unified_research_knowledge_graph_chain(self, payload: dict[str, Any]): return self.post("/research-knowledge-graph/chain-audit", payload)
    def unified_research_knowledge_graph_neighborhood(self, payload: dict[str, Any]): return self.post("/research-knowledge-graph/neighborhood", payload)
    def unified_research_knowledge_graph_path(self, payload: dict[str, Any]): return self.post("/research-knowledge-graph/path", payload)
    def export_unified_research_knowledge_graph(self, payload: dict[str, Any]): return self.post("/research-knowledge-graph/export", payload)
    def library_workspace_research_integration(self): return self.get("/workspace-integration")
    def library_workspace_research_integration_readiness(self): return self.get("/workspace-integration/readiness")
    def library_workspace_research_integration_bootstrap(self): return self.get("/workspace-integration/bootstrap")
    def build_library_to_workspace_handoff(self, payload: dict[str, Any]): return self.post("/workspace-integration/handoff/library-to-workspace", payload)
    def validate_library_workspace_handoff(self, payload: dict[str, Any]): return self.post("/workspace-integration/handoff/validate", payload)
    def preview_workspace_result_registration(self, payload: dict[str, Any]): return self.post("/workspace-integration/results/registration-preview", payload)
    def audit_library_workspace_round_trip(self, payload: dict[str, Any]): return self.post("/workspace-integration/round-trip-audit", payload)
    def export_library_workspace_exchange(self, payload: dict[str, Any]): return self.post("/workspace-integration/export", payload)
    def cross_product_research_certification(self): return self.get("/cross-product-certification")
    def cross_product_research_certification_readiness(self): return self.get("/cross-product-certification/readiness")
    def cross_product_research_certification_bootstrap(self): return self.get("/cross-product-certification/bootstrap")
    def cross_product_research_product_contract(self, product_key: str): return self.get("/cross-product-certification/products/" + parse.quote(product_key, safe=""))
    def build_cross_product_research_handoff(self, payload: dict[str, Any]): return self.post("/cross-product-certification/handoff", payload)
    def validate_cross_product_research_handoff(self, payload: dict[str, Any]): return self.post("/cross-product-certification/handoff/validate", payload)
    def cross_product_research_compatibility(self, payload: dict[str, Any]): return self.post("/cross-product-certification/compatibility", payload)
    def cross_product_research_failure_audit(self, payload: dict[str, Any]): return self.post("/cross-product-certification/failure-audit", payload)
    def certify_cross_product_research_contracts(self, payload: dict[str, Any]): return self.post("/cross-product-certification/certify", payload)
    def export_cross_product_research_certification(self, payload: dict[str, Any]): return self.post("/cross-product-certification/export", payload)
    def unified_research_project_workspace(self): return self.get("/research-project-workspace")
    def unified_research_project_workspace_readiness(self): return self.get("/research-project-workspace/readiness")
    def unified_research_project_workspace_bootstrap(self): return self.get("/research-project-workspace/bootstrap")
    def compose_unified_research_project(self, payload: dict[str, Any]): return self.post("/research-project-workspace/compose", payload)
    def validate_unified_research_project(self, payload: dict[str, Any]): return self.post("/research-project-workspace/validate", payload)
    def unified_research_project_inventory(self, payload: dict[str, Any]): return self.post("/research-project-workspace/inventory", payload)
    def unified_research_project_authority_audit(self, payload: dict[str, Any]): return self.post("/research-project-workspace/authority-audit", payload)
    def unified_research_project_dependency_summary(self, payload: dict[str, Any]): return self.post("/research-project-workspace/dependency-summary", payload)
    def unified_research_project_handoff_manifest(self, payload: dict[str, Any]): return self.post("/research-project-workspace/handoff-manifest", payload)
    def export_unified_research_project(self, payload: dict[str, Any]): return self.post("/research-project-workspace/export", payload)
    def create_citation(self, payload: dict[str, Any]): return self.post_signed("/admin/citations", payload)
    def import_citations(self, record_id: str): return self.post_signed("/admin/citations/" + parse.quote(record_id, safe="") + "/import-metadata", {})
    def citation_core_handoff(self, payload: dict[str, Any]): return self.post_signed("/admin/citations/core-handoff", payload)
    def retrieval_facets(self): return self.get("/retrieval/facets")
    def retrieval_search(self, q: str = "", **options): return self.get("/retrieval/search", {"q": q, **options})
    def retrieval_plan(self, payload: dict[str, Any]): return self.post_signed("/admin/retrieval/plan", payload)
    def retrieval_search_advanced(self, payload: dict[str, Any]): return self.post_signed("/admin/retrieval/search", payload)
    def normalize_ingestion(self, payload: dict[str, Any]): return self.post_signed("/admin/ingestion/normalize", payload)
    def ingest_source_records(self, payload: dict[str, Any]): return self.post_signed("/admin/ingestion/records", payload)
    def source_ingestion_state(self, source_key: str): return self.get_signed("/admin/ingestion/sources/" + parse.quote(source_key, safe=""))
    def research_state_for_owner(self, owner_identity_id: str): return self.get_signed("/admin/research-state/owners/" + parse.quote(owner_identity_id, safe=""))
    def create_research_project(self, payload: dict[str, Any]): return self.post_signed("/admin/research-state/projects", payload)
    def add_project_reference(self, project_id: str, payload: dict[str, Any]): return self.post_signed("/admin/research-state/projects/" + parse.quote(project_id, safe="") + "/references", payload)
    def create_source_bundle(self, project_id: str, payload: dict[str, Any]): return self.post_signed("/admin/research-state/projects/" + parse.quote(project_id, safe="") + "/bundles", payload)
    def save_search(self, payload: dict[str, Any]): return self.post_signed("/admin/research-state/saved-searches", payload)
    def save_watchlist(self, payload: dict[str, Any]): return self.post_signed("/admin/research-state/watchlists", payload)
    def enqueue_research(self, payload: dict[str, Any]): return self.post_signed("/admin/research-state/queue", payload)
    def create_collection(self, payload: dict[str, Any]): return self.post_signed("/admin/research-state/collections", payload)
    def add_collection_item(self, collection_id: str, payload: dict[str, Any]): return self.post_signed("/admin/research-state/collections/" + parse.quote(collection_id, safe="") + "/items", payload)
    def research_object(self, record_id: str, *, include_body: bool = True): return self.get("/research-objects/" + parse.quote(record_id, safe=""), {"include_body": str(include_body).lower()})
    def validate_catalog_record(self, payload: dict[str, Any]): return self.post_signed("/admin/catalog/records/validate", payload)
    def upsert_catalog_record(self, payload: dict[str, Any]): return self.post_signed("/admin/catalog/records", payload)
    def delete_catalog_record(self, record_id: str): return self.delete_signed("/admin/catalog/records/" + parse.quote(record_id, safe=""))
    def search(self, q: str = "", **filters): return self.get("/search", {"q": q, **filters})
    def record(self, record_id: str, *, include_body: bool = True): return self.get("/records/" + parse.quote(record_id, safe=""), {"include_body": str(include_body).lower()})
    def stats(self): return self.get("/stats")
    def artifacts_readiness(self): return self.get("/artifacts/readiness")
    def pipelines_readiness(self): return self.get("/pipelines/readiness")
    def compute_readiness(self): return self.get("/compute/readiness")
    def integrations(self): return self.get("/integrations")
    def submit_research_job(self, payload: dict[str, Any]): return self.post_signed("/research-jobs", payload)

    def product(self, product_key: str) -> ProductAdapter:
        if product_key not in PRODUCT_KEYS:
            raise ValueError(f"unsupported product_key: {product_key}")
        return ProductAdapter(self, product_key)

    def research_librarian(self): return self.product("research-librarian")
    def workspace(self): return self.product("workspace")
    def research_lab(self): return self.product("research-lab")
    def workbench(self): return self.product("workbench")
    def decision_studio(self): return self.product("decision-studio")
    def site_intelligence(self): return self.product("site-intelligence")
